import json
with open('missing_translations/missing_keys_korean.json', 'r', encoding='utf-8') as f:
    ko_data = json.load(f)

translations = {
  "sort.threads.by.interest.level": "관심도순으로 스레드 정렬",
  "sort.threads.by.name": "이름순으로 스레드 정렬",
  "action.text.copy.to.clipboard": "클립보드에 복사",
  "action.description.copy.whole.thread.dump.to.clipboard": "스레드 덤프 전체를 클립보드에 복사",
  "notification.text.full.thread.dump.was.successfully.copied.to.clipboard": "전체 스레드 덤프가 클립보드에 복사되었습니다",
  "notification.text.truncated.thread.dump.was.successfully.copied.to.clipboard": "잘린 스레드 덤프가 클립보드에 복사되었습니다",
  "action.description.show.only.threads.containing.a.specific.string": "특정 문자열이 포함된 스레드만 표시",
  "action.text.merge.identical.stacktraces": "동일한 스택 트레이스 병합",
  "action.description.group.threads.with.identical.stacktraces": "동일한 스택 트레이스를 가진 스레드 그룹화",
  "thread.dump.loading.text": "로드 중…",
  "truncated.dump.notification": "처음 {0}개 요소를 표시 중",
  "button.add.blank": "공백 추가",
  "button.add": "추가…",
  "button.add.package": "패키지 추가…",
  "checkbox.after.description": "설명 뒤",
  "checkbox.after.parameter.descriptions": "매개변수 설명 뒤",
  "checkbox.after.return.tag": "return 태그 뒤",
  "checkbox.align.parameter.descriptions": "매개변수 설명 정렬",
  "checkbox.align.thrown.exception.descriptions": "발생한 예외 설명 정렬",
  "checkbox.spaces.around.annotation.eq": "어노테이션 값 쌍의 '=' 주위",
  "checkbox.do.not.indent.top.level.class.members": "최상위 클래스 멤버 들여쓰기하지 않음",
  "checkbox.do.not.wrap.after.single.annotation": "단일 어노테이션 뒤 줄 바꿈하지 않음",
  "checkbox.do.not.wrap.one.line.comments": "한 줄 주석 줄 바꿈하지 않음",
  "checkbox.enable.javadoc.formatting": "JavaDoc 포맷팅 사용",
  "checkbox.enable.leading.asterisks": "앞행 별표 사용",
  "checkbox.generate.p.on.empty.lines": "빈 줄에 \"<p>\" 생성",
  "checkbox.insert.imports.for.inner.classes": "내부 클래스에 대한 import 추가",
  "checkbox.keep.empty.lines": "빈 줄 유지",
  "checkbox.keep.empty.param.tags": "빈 @param 태그 유지",
  "checkbox.keep.empty.return.tags": "빈 @return 태그 유지",
  "checkbox.keep.empty.throws.tags": "빈 @throws 태그 유지",
  "checkbox.keep.invalid.tags": "잘못된 태그 유지",
  "checkbox.param.description.on.new.line": "매개변수 설명을 새 줄에 표시",
  "checkbox.param.indent.on.continuation": "연속 줄 들여쓰기",
  "checkbox.preserve.line.feeds": "줄 바꿈 문자(line feed) 유지",
  "checkbox.spaces.record.header": "레코드 헤더",
  "checkbox.spaces.within.deconstruction.list": "구조 분해 목록",
  "checkbox.spaces.inside.block.braces.when.body.is.present": "본문이 있을 때 블록 중괄호 안쪽",
  "checkbox.spaces.before.colon.in.foreach": "foreach 코론(:) 앞",
  "checkbox.spaces.before.deconstruction.list": "구조 분해 목록",
  "checkbox.spaces.inside.one.line.enum": "한 줄 안의 enum 중괄호 안쪽",
  "checkbox.use.fully.qualified.class.names": "정규화된 클래스 이름(fully qualified class names) 사용",
  "checkbox.use.single.class.import": "단일 클래스 import 사용",
  "checkbox.no.separate.module.import": "모듈 import를 단일 클래스나 패키지 import로 분리하지 않음",
  "checkbox.delete.unused.module.import": "사용하지 않는 모듈 import 제거",
  "checkbox.use.throws.rather.than.exception": "@exception 대신 @throws 사용",
  "checkbox.wrap.at.right.margin": "오른쪽 여백에서 줄 바꿈",
  "code.style.settings.angle.spacing.brackets": "꺾쇠 괄호",
  "code.style.settings.spacing.after.closing.angle.bracket": "닫기 꺾쇠 괄호 뒤",
  "code.style.settings.spacing.around.type.bounds": "유형 범위(type bounds) 주위",
  "editbox.blanklines.around.initializer": "이니셜라이저 주위:",
  "editbox.blank.lines.field.in.interface": "인터페이스의 필드 앞",
  "editbox.blank.lines.field.without.annotations": "어노테이션이 없는 필드 앞:",
  "editbox.blank.lines.field.with.annotations": "어노테이션이 있는 필드 앞:",
  "editbox.blank.lines.record.components": "레코드 구성요소 사이:",
  "editbox.class.count.to.use.import.with.star": "'*'를 사용할 import 클래스 수:",
  "editbox.names.count.to.use.static.import.with.star": "'*'를 사용할 정적(static) import 이름 수:",
  "title.import.layout": "import 레이아웃:",
  "title.packages.to.use.import.with": "'*'구문과 사용할 패키지:",
  "wrapping.semicolon.after.call.chain": "호출 체인 뒤의 ';'를 새 줄로 이동",
  "wrapping.annotation.enums": "Enum 필드 어노테이션",
  "wrapping.annotation.parameters": "어노테이션 매개변수",
  "wrapping.record.components": "레코드 구성요소",
  "wrapping.multi.catch.types": "multi-catch의 유형",
  "wrapping.deconstruction.patterns": "구조 분해 패턴",
  "wrapping.text.blocks": "텍스트 블록",
  "new.line.when.body.is.presented": "본문이 있을 때 새 줄",
  "annotations.new.line.record.component": "어노테이션을 새 줄로",
  "align.types.in.multi.catch": "multi-catch에서 유형 정렬",
  "wrapping.switch.statement.or.expression": "'switch' 구문/표현식",
  "auto.run.floating.toolbar.text": "자동 테스트 켜기",
  "auto.run.floating.toolbar.disable.action": "자동 테스트 끄기",
  "title.javadoc": "JavaDoc",
  "group.javadoc.other": "기타",
  "group.javadoc.alignment": "정렬",
  "group.javadoc.blank.lines": "빈 줄",
  "group.javadoc.invalid.tags": "잘못된 태그",
  "radio.use.fully.qualified.class.names.in.javadoc": "JavaDoc에서 정규화된 클래스 이름 사용:",
  "radio.use.fully.qualified.class.names.in.javadoc.always": "항상",
  "radio.use.fully.qualified.class.names.in.javadoc.if.not.imported": "아직 import되지 않은 경우",
  "radio.use.fully.qualified.class.names.in.javadoc.never": "절대 사용 안 함, 짧은 이름을 사용하고 import 추가",
  "import.layout.static.imports.separately": "정적(static) import를 별도로 배치",
  "import.layout.on.demand.import.from.same.package.first": "동일 패키지 내부 단일 클래스 import보다 온디맨드 import를 앞쪽에 배치",
  "import.layout.panel.up.button": "위로",
  "import.layout.panel.down.button": "아래로",
  "import.layout.panel.blank.line.entry": "<빈 줄>",
  "import.layout.panel.all.other.imports": "다른 모든 import",
  "import.layout.panel.module.imports": "모듈 import",
  "listbox.import.package": "패키지",
  "listbox.import.static": "정적(Static)",
  "listbox.import.with.subpackages": "하위 패키지 포함",
  "do.not.import.inner.classes.for": "짧은 이름을 기반으로 내부 클래스 제외:",
  "do.not.import.inner.classes.no.classes": "정의된 내부 클래스 없음",
  "dump.item.java.thread.icon.tooltip.virtual": "가상(Virtual) 스레드",
  "dump.item.java.thread.icon.tooltip.daemon": "데몬(Daemon) 스레드"
}

ko_error_bundle = next((x for x in ko_data['new_files'] if x['filename'] == 'JavaFrontbackBundle.properties'), None)
if not ko_error_bundle:
    ko_error_bundle = {'filename': 'JavaFrontbackBundle.properties', 'keys': {}, 'key_count': 0}
    ko_data['new_files'].append(ko_error_bundle)
ko_error_bundle['keys'].update(translations)
ko_error_bundle['key_count'] = len(ko_error_bundle['keys'])

with open('missing_translations/missing_keys_korean.json', 'w', encoding='utf-8') as f:
    json.dump(ko_data, f, ensure_ascii=False, indent=2)

print("Updated JavaFrontbackBundle.properties")
