import json

ko_dict = {
  "fix.change.to.function.invocation": "함수 호출로 변경",
  "fix.change.to.mutable.type.family": "변경 가능한 유형으로 변경",
  "fix.change.to.mutable.type.text": "유형을 {0}(으)로 변경",
  "fix.change.to.property.access.family.remove": "호출 제거",
  "fix.change.to.property.access.family.change": "속성 액세스로 변경",
  "fix.change.to.labeled.return.family": "레이블이 있는 return으로 변경",
  "fix.change.to.labeled.return.text": "''{0}''(으)로 변경",
  "fix.change.suspend.hierarchy.add": "계층 구조의 모든 함수에 'suspend' 제어자 추가",
  "fix.change.suspend.hierarchy.remove": "계층 구조의 모든 함수에서 'suspend' 제어자 제거",
  "fix.change.progress.looking.inheritors": "클래스 {0} 상속자 찾는 중…",
  "fix.change.progress.analyzing.class.hierarchy": "클래스 계층 구조 분석 중…",
  "fix.change.return.type.family": "유형 변경",
  "fix.change.return.type.text.primary.constructor": "클래스 ''{1}''의 기본 생성자 매개변수 ''{0}'' 유형을 ''{2}''(으)로 변경",
  "fix.change.return.type.text.function": "함수 ''{1}''의 매개변수 ''{0}'' 유형을 ''{2}''(으)로 변경",
  "fix.change.return.type.command.primary.constructor": "클래스 ''{1}''의 기본 생성자 매개변수 ''{0}'' 유형을 ''{2}''(으)로 변경",
  "fix.change.return.type.command.function": "함수 ''{1}''의 매개변수 ''{0}'' 유형을 ''{2}''(으)로 변경",
  "fix.change.return.type.lambda": "람다 표현식 반환 유형을 {0}(으)로 변경",
  "fix.change.return.type.remove.explicit.return.type": "명시적으로 지정된 반환 유형 제거",
  "fix.change.return.type.remove.explicit.return.type.of": "{0}의 명시적으로 지정된 반환 유형 제거",
  "fix.change.return.type.return.type.text": "반환 유형을 ''{0}''(으)로 변경",
  "fix.change.return.type.return.type.text.of": "{0}의 반환 유형을 ''{1}''(으)로 변경",
  "fix.change.return.type.type.text": "유형을 ''{0}''(으)로 변경",
  "fix.change.return.type.type.text.of": "{0}의 유형을 ''{1}''(으)로 변경",
  "fix.change.return.type.presentation.property": "속성 {0}",
  "fix.change.return.type.presentation.function": "함수 {0}",
  "fix.change.return.type.presentation.enclosing.function": "둘러싸는 함수",
  "fix.change.return.type.presentation.enclosing": "{0} 둘러싸기",
  "fix.change.return.type.presentation.called.function": "호출된 함수",
  "fix.change.return.type.presentation.accessed": "액세스된 {0}",
  "fix.change.return.type.presentation.called": "호출된 {0}",
  "fix.change.return.type.presentation.base": "기본 {0}",
  "fix.cast.expression.family": "표현식 변환",
  "fix.cast.expression.text": "표현식 ''{0}''을(를) ''{1}''(으)로 변환",
  "fix.change.accessor.family": "접근자 유형 변경",
  "fix.change.accessor.getter": "getter 유형을 {0}(으)로 변경",
  "fix.change.accessor.setter.parameter": "setter 매개변수 유형을 {0}(으)로 변경",
  "fix.create.from.usage.dialog.title": "사용에서 생성",
  "fix.add.remaining.branches": "나머지 분기 추가",
  "fix.add.remaining.branches.with.star.import": "* 가져오기로 나머지 분기 추가",
  "fix.add.type.annotation.family": "유형 주석 추가",
  "fix.add.type.annotation.text": "매개변수 ''{1}''에 ''{0}'' 유형 추가",
  "fix.add.tostring.call.family": "'toString()' 호출 추가",
  "fix.add.tostring.call.text": "'toString()' 호출 추가",
  "fix.add.tostring.call.text.safe": "안전한 '?.toString()' 호출 추가",
  "fix.add.star.projection.family": "별표 프로젝션 추가",
  "fix.add.star.projection.text": "''{0}'' 추가",
  "fix.change.to.star.projection.family": "별표 프로젝션으로 변경",
  "fix.change.to.star.projection.text": "유형 인수를 {0}(으)로 변경",
  "fix.change.to.use.spread.operator.family": "스프레드 연산자를 사용하도록 변경",
  "fix.change.to.use.spread.operator.text": "''{0}''을(를) ''{1}''(으)로 변경",
  "fix.change.type.family": "유형 변경",
  "fix.change.type.text": "유형을 ''{0}''에서 ''{1}''(으)로 변경",
  "fix.add.suspend.modifier.function": "{0}을(를) suspend로 만들기",
  "fix.add.suspend.modifier.function.generic": "포함하는 함수를 suspend로 만들기",
  "fix.add.suspend.modifier.receiver": "{0} 유형을 suspend로 만들기",
  "fix.add.suspend.modifier.receiver.generic": "수신자 유형을 suspend로 만들기",
  "fix.add.function.parameters.change.signature.constructor": "생성자 ''{0}''의 서명 변경",
  "fix.add.function.parameters.change.signature.function": "함수 ''{0}''의 서명 변경",
  "fix.add.function.parameters.add.parameter.constructor": "생성자 ''{2}''에 {1}({0}번째) 추가",
  "fix.add.function.parameters.add.parameter.function": "함수 ''{2}''에 {1}({0}번째) 추가",
  "fix.add.function.parameters.add.parameter.generic.constructor": "생성자 ''{1}''에 {0} 추가",
  "fix.add.function.parameters.add.parameter.generic.function": "함수 ''{1}''에 {0} 추가",
  "fix.change.signature.family": "함수/생성자 서명 변경",
  "fix.change.signature.function.family": "함수 서명 변경",
  "fix.change.signature.function.text": "함수 서명을 ''{0}''(으)로 변경",
  "fix.change.signature.function.text.generic": "함수 서명 변경…",
  "fix.change.signature.function.popup.title": "서명 선택",
  "fix.change.signature.lambda": "람다 표현식의 서명 변경",
  "fix.change.signature.lambda.command": "람다 표현식의 서명 변경",
  "fix.change.signature.remove.parameter": "매개변수 ''{0}'' 제거",
  "fix.change.signature.remove.parameter.command": "매개변수 ''{0}'' 제거",
  "fix.change.signature.unavailable": "<사용 불가>",
  "fix.change.signature.error": "<오류>",
  "fix.change.signature.unnamed.parameter": "매개변수",
  "fix.change.signature.prepare": "준비 중…",
  "fix.change.object.to.class": "'object'를 'class'로 변경",
  "fix.add.member.supertype.family": "상위 유형에 {0} 추가",
  "fix.add.member.supertype.text": "상위 유형에 {0} 추가…",
  "fix.add.member.supertype.progress": "유형에 {0} 추가",
  "fix.add.member.supertype.choose.type": "유형 선택",
  "fix.add.member.supertype.add.to": "''{1}''에 ''{0}'' 추가",
  "fix.add.generic.upperbound.text": "{1}의 상한으로 ''{0}'' 추가",
  "fix.add.generic.upperbound.family": "제네릭 상한 추가",
  "fix.make.upperbound.not.nullable.any.text": "{0}의 상한으로 ''Any''를 추가하여 Null을 허용하지 않도록 함",
  "fix.make.upperbound.not.nullable.remove.nullability.text": "{0}의 상한을 ''{1}''(으)로 변경하여 {0}이(가) null을 허용하지 않도록 함",
  "fix.make.upperbound.not.nullable.family": "제네릭 유형 매개변수가 Null을 허용하지 않도록 설정",
  "fix.add.modifier.inline.parameter.family": "매개변수에 ''{0}'' 추가",
  "fix.add.modifier.inline.parameter.text": "매개변수 ''{1}''에 ''{0}'' 추가",
  "fix.add.modifier.inline.function.family": "함수에 'inline' 추가",
  "fix.add.modifier.inline.function.text": "함수 ''{0}''에 ''inline'' 추가",
  "fix.add.array.of.type.text": "{0} 래퍼 추가",
  "fix.add.array.of.type.family": "'arrayOf' 래퍼 추가",
  "fix.add.loop.label.text.generic": "루프에 레이블 추가",
  "fix.add.loop.label.text": "{1}에 ''{0}'' 추가",
  "fix.add.modifier.family": "제어자 추가",
  "fix.add.modifier.text": "{0}을(를) ''{1}''(으)로 설정",
  "fix.add.modifier.text.generic": "''{0}'' 제어자 추가",
  "fix.potentially.broken.inheritance.message": "이 변경으로 인해 상속자가 손상될 수 있습니다.",
  "fix.make.field.public.text": "필드 ''{0}''을(를) public으로 만들기",
  "fix.make.field.public.family": "필드를 public으로 만들기"
}

with open('missing_translations/missing_keys_korean.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

filename = "KotlinBundle.properties"
found = False
for file_entry in data.get('new_files', []):
    if file_entry['filename'] == filename:
        file_entry['keys'].update(ko_dict)
        found = True
        break
if not found:
    data.setdefault('new_files', []).append({"filename": filename, "keys": ko_dict})

print(f"Updated {filename} (Keys 41-140)")

with open('missing_translations/missing_keys_korean.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
