# Original path: C:\Program Files\Android\Android Studio\lib\modules\intellij.platform.vcs.dvcs.jar!/messages/VcsProductivityFeatures.properties
# Extracted on: 2026-04-01 21:36:46

# suppress inspection "UnusedProperty"
vcs.show.quick.list=Show VCS quick list
vcs.pull.requests=Show pull requests
vcs.use.integration=Use VCS Integration
vcs.compare.file.versions=Compare file versions
vcs.partial.commit=Partial commit
vcs.annotate=Annotate with Git Blame