# ═════════════════════════════════════════════════════════════════════════════
# buildBundle - Korean Translation
# Android Studio 한국어 언어팩
# ═════════════════════════════════════════════════════════════════════════════
# 생성일: 2026-03-28 19:10:06
# 자동 생성된 파일입니다.
# ═════════════════════════════════════════════════════════════════════════════

buildNumber=4c87b05d9aedce574290d1acc98575ed5eb6cd39
version=3.8.8
distributionId=apache-maven
distributionShortName=Maven
distributionName=Apache Maven
