############################################################################### 
# Copyright (c) 2000, 2011 IBM Corporation and others.
#
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     IBM Corporation - initial API and implementation
#     QNX Software Systems
#     Anton Leherbauer (Wind River Systems)
#     Markus Schorn (Wind River Systems)
############################################################################### 

### CCorePlugin plugin messages.

CCorePlugin.startup_message = cdt.core 초기화 중

ScannerProvider.Info_Provider_Error=스캐너 정보 제공자 오류
ScannerProvider.Error_Provider=스캐너 정보 제공자를 생성하는 중 오류가 발생했습니다\: 클래스 \={0}, 확장 ID \={1}

ContentParser.Error_Provider=컨텐츠 유형의 파서를 생성하는 중 오류가 발생했습니다\: 파서 id \={0}
Error_CIndexer=인덱서를 생성하는 중 오류가 발생했습니다\: 파서 id \={0}

### CErrors
Exception.projectNull = 프로젝트가 null입니다
Exception.builderIsNull = 빌더가 null입니다
Exception.builderNameIsNull = 빌더 이름이 null입니다
Exception.makeError = {0} 오류

### Error Parser
ErrorParser.Command_Error=C/C++ 빌더 예외.
CoreModelProvider.0=알 수 없는 파일입니다
ProjectUpdateOperation.0=초기화 오류
ProjectUpdateOperation.1={0}의 프로젝트 설명을 업데이트할 수 없습니다

### CModelBuilder
CModelBuilder.parsing = 파싱 중

### GCC ScannerInfo messages
ScannerInfoProvider.Finding_Scanner_Info=스캐너 정보 검색 중
ScannerInfoProvider.Parsing_Output=출력 파싱 중
ScannerInfoProvider.Reading_Specs=사양(Specs) 읽는 중
ScannerInfoProvider.Error_While_Fetching_Scanner_Info=스캐너 정보를 가져오는 중 오류가 발생했습니다
GccScannerInfoProvider.No_Includes=제공자가 '{0}'에 대한 포함(include)을 찾지 못했습니다. 매크로 및 외부 포함을 확인해 보세요.

Indexer.Task_Name=C/C++ 파일 인덱싱
Indexer.Error=C/C++ 인덱스 작성 중 오류 발생
IndexJob.error.notSetup=인덱스가 초기화되지 않아 인덱서 작업을 취소합니다.    

Util.processError=({0}) 실행 오류 \: {1}
Util.exception=예외 발생
Util.processNotConfigured=외부 프로그램을 실행할 수 없습니다. 필요한 속성이 지정되지 않았습니다.

CExtension.instatiationError={1} 요소 내의 {0} 확장을 인스턴스화하는 중 C Extension 오류 발생

StandardManageConfig.info.configNotFound=구성을 찾을 수 없음\: {0}

DependencyManager.no_project=C/C++ 프로젝트를 찾을 수 없음
DependencyManager.no_build_info=C/C++ 빌더에 대한 빌드 정보를 찾을 수 없습니다. 프로젝트\: {0}

ProjectNature.missingProvider=속성 및 버전 제공자와 C/C++ 네이처를 연결하는 중 누락된 제공자를 발견했습니다\: {0}

LanguageManager.missingProvider=언어와 언어 제공자를 연결하는 중 잘못된 확장 지점 언어가 발견되었습니다\: {0} (제공자\: {1})
LanguageManager.conflictingModifiers=언어 {0}에 충돌하는 수정자 확장 지점이 로드되었습니다
LanguageManager.conflictingWorkspaceModifiers=언어 {0}의 작업 공간(Workspace)에 충돌하는 수정자가 로드되었습니다
CProjectDescriptionManager.0=프로젝트 {0}의 설정 로드 실패 (알 수 없는 C/C++ 프로젝트)
CProjectDescriptionManager.1=C/C++ 프로젝트 설정 지정 중
PathEntryManager.0=경로 항목 처리 중 오류 발생
PathEntryManager.1=설정 직렬화 중...
PathEntryManager.2=경로 항목 비동기 설정 중

UpdateProject_status_message=더 이상 사용되지 않는 설정을 업데이트하는 중 오류가 발생했습니다
CommandLauncher.error.commandCanceled=명령이 취소됨
CommandLauncher.error.commandNotFound=프로그램을 찾을 수 없음
ErrorParserManager.0=문자열을 생성할 수 없습니다

MakeUtil_unsupported_project_settings_node=지원되지 않는 cdt 프로젝트 설정 노드\: {0}
MakeUtil_unsupported_cdt_project_settings_version=지원되지 않는 cdt 프로젝트 설정 버전\: {0}

ScannerDiscovery.Message=스캐너 정보 검색 중
ScannerDiscovery.Info_Provider_Error=발견 및 수집 프로필 작업 중 스캐너 초기화 오류가 발생했습니다 (발견 프로필 ID\: {0})

IncludeExport_0=파일 {0}의 IncludeExport 특성을 확인하고 있습니다.
CConfigBasedDescriptor_0=이 플러그인에 대한 구성 설명 생성에 실패했습니다\: {0} 
CConfigBasedDescriptor_1=저장할 수 없습니다, CConfigurationDescription이 읽기 전용입니다

DefaultCIndex.0=새 인덱스의 작업 공간 상태가 이전에 일시 중지된 인덱스 작업에서 변경되었습니다. 새로운 전체 인덱스를 시작합니다.
PDOMManager.0=인덱스 작업 보류 중

CProject.Cannot_delete=프로젝트 설명 캐시를 삭제할 수 없습니다.

XmlUtil_InternalErrorLoading=XML 구문 분석 중 내부 오류 발생... XML 문서의 형식을 잘못 지정했을 가능성이 큽니다...
XmlUtil_InternalErrorSerializing=XML 문서 직렬화 중 내부 오류 발생
