#
# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.      
# See the License for the specific language governing permissions and
# limitations under the License.
#
le.status.in_progress.title=업데이트 중
le.status.in_progress.description=실시간 수정(Live Edit)을 업데이트하는 중입니다.
le.status.loading.title=로딩 중
le.status.loading.description=앱을 배포하는 중입니다...
le.status.up_to_date.title=최신 상태
le.status.up_to_date.description_auto=앱이 최신 상태입니다. 코드 변경 사항이 실행 중인 앱에 자동으로 적용됩니다.
le.status.up_to_date.description_manual=앱이 최신 상태입니다. 새로고침 시 코드 변경 사항이 실행 중인 앱에 적용됩니다.
le.status.out_of_date.title=최신 버전 아님
le.status.out_of_date.description=최신 실시간 수정(Live Edit) 변경 사항을 보려면 새로고침하세요. 앱 상태가 재설정될 수 있습니다.
le.status.no_multi_deploy.description=다른 기기에서의 최신 배포로 인해 이 기기에서는 실시간 수정(Live Edit)이 자동으로 비활성화되었습니다.
le.status.recompose_needed.title=Recompose 필요
le.status.recompose_needed.description=모든 변경 사항이 적용되려면 하드 새로고침이 수행되어야 합니다. 앱 상태가 재설정됩니다.
le.status.error.recompose.title=Recomposition 오류
le.status.error.recompose.description=Recomposition 중에 애플리케이션에 예기치 않은 예외가 발생하여 마지막으로 성공한 구성 상태로 되돌아갔습니다.
le.status.error.debugger_attached.title=실시간 수정(Live Edit) 미지원
le.status.error.debugger_attached.description=앱이 현재 디버깅 모드로 실행 중입니다. 이 모드는 실시간 수정(Live Edit)과 호환되지 않습니다.
le.status.error.gradle_sync.title=Gradle 동기화 필요
le.status.error.gradle_sync.description=Gradle 동기화를 수행해야 합니다. 동기화하고 앱을 다시 실행하세요.
le.status.error.unsupported_version.title=지원되지 않는 API
le.status.error.unsupported_version.description=최신 실시간 수정(Live Edit) 변경 사항을 보려면 에뮬레이터/기기 API 수준을 30 이상으로 업데이트하세요.
le.status.error.unsupported_version_other.description=배포된 애플리케이션이 있는 일부 기기에서 API 수준 30 이상을 사용하지 않고 있습니다. 배포된 모든 기기가 실시간 수정(Live Edit)을 지원할 때까지 실시간 수정(Live Edit)은 중지됩니다.
le.status.pre_compiling.title=현재 파일 준비 중
le.status.pre_compiling.description=현재 파일에 대한 diff 기준을 생성하는 중입니다
le.build.redeploy.title=다시 빌드 및 재배포
le.build.redeploy.description=기기에서 앱을 새로고침합니다.

le.save.deploy.title=저장 및 변경 사항 배포
