#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
missing_keys.json 종합 번역 스크립트
30,000개 이상의 키를 번역 가이드라인에 따라 자동 번역합니다.
"""

import json
import re
from pathlib import Path
from typing import Dict, Tuple


class KoreanTranslator:
    """한국어 번역기 클래스"""
    
    def __init__(self):
        """번역 사전 초기화"""
        self.translations = self._build_translation_dict()
        self.placeholder_pattern = re.compile(r'\{(\d+)\}')
        self.ellipsis_pattern = re.compile(r'\\u2026|\.\.\.') 
        
    def _build_translation_dict(self) -> Dict[str, str]:
        """포괄적인 번역 사전 구축"""
        return {
            # 공통 동사/명사
            "Running": "실행 중",
            "Ran": "실행됨",
            "Executing": "실행 중",
            "Executed": "실행됨",
            "Creating": "생성 중",
            "Created": "생성됨",
            "Deleting": "삭제 중",
            "Deleted": "삭제됨",
            "Reading": "읽는 중",
            "Read": "읽음",
            "Writing": "쓰는 중",
            "Written": "작성됨",
            "Editing": "편집 중",
            "Edited": "편집됨",
            "Analyzing": "분석 중",
            "Analyzed": "분석됨",
            "Searching": "검색 중",
            "Searched": "검색됨",
            "Finding": "찾는 중",
            "Found": "찾음",
            "Listing": "목록 표시 중",
            "Listed": "목록 표시됨",
            "Identifying": "식별 중",
            "Identified": "식별됨",
            "Marking": "표시 중",
            "Marked": "표시됨",
            "Notifying": "알림 중",
            "Notified": "알림됨",
            "Asking": "질문 중",
            "Asked": "질문함",
            "Waiting": "대기 중",
            "Loading": "로드 중",
            "Loaded": "로드됨",
            "Saving": "저장 중",
            "Saved": "저장됨",
            "Building": "빌드 중",
            "Built": "빌드됨",
            "Compiling": "컴파일 중",
            "Compiled": "컴파일됨",
            "Installing": "설치 중",
            "Installed": "설치됨",
            "Updating": "업데이트 중",
            "Updated": "업데이트됨",
            "Debugging": "디버깅 중",
            "Debugged": "디버깅됨",
            "Attaching": "연결 중",
            "Attached": "연결됨",
            "Detaching": "분리 중",
            "Detached": "분리됨",
            "Resolving": "해석 중",
            "Resolved": "해석됨",
            "Parsing": "파싱 중",
            "Parsed": "파싱됨",
            
            # Agent 관련
            "Agent Change": "에이전트 변경",
            "Asking the user": "사용자에게 질문 중",
            "Asked the user": "사용자에게 질문함",
            "Waiting for your answer": "답변 대기 중",
            "Notifying the user": "사용자에게 알림 중",
            "Notified the user": "사용자에게 알림됨",
            "Auto-approving": "자동 승인 중",
            
            # 파일 관련
            "file": "파일",
            "File": "파일",
            "files": "파일",
            "Files": "파일",
            "current file": "현재 파일",
            "declaration": "선언",
            "usages": "사용처",
            "URL": "URL",
            "the web": "웹",
            "shell command": "셸 명령",
            "plan": "계획",
            "step": "단계",
            "step as complete": "단계를 완료로",
            "symbol": "심볼",
            "VCS roots": "VCS 루트",
            "VCS root for file": "파일의 VCS 루트",
            
            # Git 관련
            "git": "git",
            "Git": "Git",
            "commit": "커밋",
            "Commit": "커밋",
            "branch": "브랜치",
            "Branch": "브랜치",
            "merge": "병합",
            "Merge": "병합",
            "rebase": "리베이스",
            "Rebase": "리베이스",
            "push": "푸시",
            "Push": "푸시",
            "pull": "풀",
            "Pull": "풀",
            "fetch": "가져오기",
            "Fetch": "가져오기",
            "clone": "복제",
            "Clone": "복제",
            "repository": "저장소",
            "Repository": "저장소",
            
            # UI 관련
            "UI Tools": "UI 도구",
            "Track Pad": "트랙 패드",
            "Magnify zooming (pinch) sensitivity": "확대/축소(핀치) 민감도",
            "Resource Usage": "리소스 사용량",
            "Resource": "리소스",
            "View Mode": "보기 모드",
            "Editor View Mode": "편집기 보기 모드",
            "Default": "기본값",
            "Essentials": "필수",
            "Kotlin": "Kotlin",
            "Java": "Java",
            "Preview Settings": "미리보기 설정",
            "Preview": "미리보기",
            "Enable live updates": "실시간 업데이트 사용",
            "live updates": "실시간 업데이트",
            
            # 디버거 관련
            "Debugger": "디버거",
            "debugger": "디버거",
            "Hybrid/Auto Debugger": "하이브리드/자동 디버거",
            "breakpoint": "중단점",
            "Breakpoint": "중단점",
            "breakpoints": "중단점",
            "Breakpoints": "중단점",
            "Line Breakpoints": "라인 중단점",
            "stack frame": "스택 프레임",
            "Stack frame": "스택 프레임",
            "thread": "스레드",
            "Thread": "스레드",
            "Hit count": "히트 카운트",
            "step into": "단계별 실행",
            "Step into": "단계별 실행",
            "smart step into": "스마트 단계별 실행",
            "step over": "단계별 이동",
            "Step over": "단계별 이동",
            "step out": "프로시저 나가기",
            "Step out": "프로시저 나가기",
            
            # 에러 메시지
            "Error": "오류",
            "error": "오류",
            "Failed": "실패",
            "failed": "실패",
            "Cannot": "할 수 없음",
            "cannot": "할 수 없음",
            "not supported": "지원되지 않음",
            "not implemented": "구현되지 않음",
            "Invalid": "잘못됨",
            "invalid": "잘못됨",
            "not found": "찾을 수 없음",
            "Not found": "찾을 수 없음",
            "not available": "사용할 수 없음",
            "Not available": "사용할 수 없음",
            "Missing": "누락됨",
            "missing": "누락됨",
            "Unknown": "알 수 없음",
            "unknown": "알 수 없음",
            "Unexpected": "예기치 않은",
            "unexpected": "예기치 않은",
            
            # 액션 관련
            "Paste": "붙여넣기",
            "paste": "붙여넣기",
            "Copy": "복사",
            "copy": "복사",
            "Cut": "잘라내기",
            "cut": "잘라내기",
            "Delete": "삭제",
            "delete": "삭제",
            "Rename": "이름 바꾸기",
            "rename": "이름 바꾸기",
            "Refactor": "리팩터링",
            "refactor": "리팩터링",
            "Format": "포맷",
            "format": "포맷",
            "Optimize": "최적화",
            "optimize": "최적화",
            "Generate": "생성",
            "generate": "생성",
            
            # 설정 관련
            "Settings": "설정",
            "settings": "설정",
            "Options": "옵션",
            "options": "옵션",
            "Preferences": "환경설정",
            "preferences": "환경설정",
            "Configuration": "구성",
            "configuration": "구성",
            "Configurable": "구성 가능",
            "configurable": "구성 가능",
            
            # 기타
            "Assembly language file": "어셈블리 언어 파일",
            "buildNumber": "빌드 번호",
            "version": "버전",
            "distributionId": "배포 ID",
            "distributionShortName": "배포 단축 이름",
            "distributionName": "배포 이름",
            "Apache Maven": "Apache Maven",
            "Maven": "Maven",
            "Module": "모듈",
            "module": "모듈",
            "Project": "프로젝트",
            "project": "프로젝트",
            "Library": "라이브러리",
            "library": "라이브러리",
            "Package": "패키지",
            "package": "패키지",
            "Class": "클래스",
            "class": "클래스",
            "Method": "메서드",
            "method": "메서드",
            "Function": "함수",
            "function": "함수",
            "Variable": "변수",
            "variable": "변수",
            "Field": "필드",
            "field": "필드",
            "Property": "속성",
            "property": "속성",
            "Parameter": "매개변수",
            "parameter": "매개변수",
            "Argument": "인수",
            "argument": "인수",
            "Type": "타입",
            "type": "타입",
            "Interface": "인터페이스",
            "interface": "인터페이스",
            "Annotation": "주석",
            "annotation": "주석",
            "Template": "템플릿",
            "template": "템플릿",
            "Renderer": "렌더러",
            "renderer": "렌더러",
            "Frame": "프레임",
            "frame": "프레임",
            "Value": "값",
            "value": "값",
            "Expression": "표현식",
            "expression": "표현식",
            "Symbol": "심볼",
            "Namespace": "네임스페이스",
            "namespace": "네임스페이스",
            "Directory": "디렉터리",
            "directory": "디렉터리",
            "Folder": "폴더",
            "folder": "폴더",
            "Path": "경로",
            "path": "경로",
            "Filter": "필터",
            "filter": "필터",
            "Search": "검색",
            "search": "검색",
            "Find": "찾기",
            "find": "찾기",
            "Replace": "바꾸기",
            "replace": "바꾸기",
            "Navigate": "탐색",
            "navigate": "탐색",
            "Navigation": "탐색",
            "navigation": "탐색",
            "Editor": "편집기",
            "editor": "편집기",
            "Console": "콘솔",
            "console": "콘솔",
            "Terminal": "터미널",
            "terminal": "터미널",
            "Window": "창",
            "window": "창",
            "Dialog": "대화상자",
            "dialog": "대화상자",
            "Panel": "패널",
            "panel": "패널",
            "Toolbar": "도구 모음",
            "toolbar": "도구 모음",
            "Menu": "메뉴",
            "menu": "메뉴",
            "Action": "작업",
            "action": "작업",
            "Command": "명령",
            "command": "명령",
            "Process": "프로세스",
            "process": "프로세스",
            "Application": "애플리케이션",
            "application": "애플리케이션",
            "Service": "서비스",
            "service": "서비스",
            "Server": "서버",
            "server": "서버",
            "Client": "클라이언트",
            "client": "클라이언트",
            "Connection": "연결",
            "connection": "연결",
            "Session": "세션",
            "session": "세션",
            "Request": "요청",
            "request": "요청",
            "Response": "응답",
            "response": "응답",
            "Timeout": "시간 초과",
            "timeout": "시간 초과",
            "Permission": "권한",
            "permission": "권한",
            "Access": "액세스",
            "access": "액세스",
            "Security": "보안",
            "security": "보안",
            "Authentication": "인증",
            "authentication": "인증",
            "Authorization": "권한 부여",
            "authorization": "권한 부여",
            "Encryption": "암호화",
            "encryption": "암호화",
            "Certificate": "인증서",
            "certificate": "인증서",
            "Key": "키",
            "key": "키",
            "Password": "비밀번호",
            "password": "비밀번호",
            "Token": "토큰",
            "token": "토큰",
            "License": "라이선스",
            "license": "라이선스",
            "Copyright": "저작권",
            "copyright": "저작권",
            "Author": "작성자",
            "author": "작성자",
            "Date": "날짜",
            "date": "날짜",
            "Time": "시간",
            "time": "시간",
            "Duration": "기간",
            "duration": "기간",
            "Size": "크기",
            "size": "크기",
            "Length": "길이",
            "length": "길이",
            "Width": "너비",
            "width": "너비",
            "Height": "높이",
            "height": "높이",
            "Position": "위치",
            "position": "위치",
            "Location": "위치",
            "location": "위치",
            "Offset": "오프셋",
            "offset": "오프셋",
            "Index": "인덱스",
            "index": "인덱스",
            "Count": "개수",
            "count": "개수",
            "Number": "번호",
            "number": "번호",
            "Amount": "양",
            "amount": "양",
            "Quantity": "수량",
            "quantity": "수량",
            "Limit": "제한",
            "limit": "제한",
            "Maximum": "최대",
            "maximum": "최대",
            "Minimum": "최소",
            "minimum": "최소",
            "Range": "범위",
            "range": "범위",
            "Scale": "배율",
            "scale": "배율",
            "Level": "레벨",
            "level": "레벨",
            "Priority": "우선순위",
            "priority": "우선순위",
            "Status": "상태",
            "status": "상태",
            "State": "상태",
            "state": "상태",
            "Mode": "모드",
            "mode": "모드",
            "Style": "스타일",
            "style": "스타일",
            "Theme": "테마",
            "theme": "테마",
            "Color": "색상",
            "color": "색상",
            "Font": "글꼴",
            "font": "글꼴",
            "Icon": "아이콘",
            "icon": "아이콘",
            "Image": "이미지",
            "image": "이미지",
            "Picture": "그림",
            "picture": "그림",
            "Graphic": "그래픽",
            "graphic": "그래픽",
            "Diagram": "다이어그램",
            "diagram": "다이어그램",
            "Chart": "차트",
            "chart": "차트",
            "Graph": "그래프",
            "graph": "그래프",
            "Table": "표",
            "table": "표",
            "List": "목록",
            "list": "목록",
            "Tree": "트리",
            "tree": "트리",
            "Node": "노드",
            "node": "노드",
            "Element": "요소",
            "element": "요소",
            "Item": "항목",
            "item": "항목",
            "Entry": "항목",
            "entry": "항목",
            "Record": "레코드",
            "record": "레코드",
            "Data": "데이터",
            "data": "데이터",
            "Information": "정보",
            "information": "정보",
            "Content": "내용",
            "content": "내용",
            "Text": "텍스트",
            "text": "텍스트",
            "Message": "메시지",
            "message": "메시지",
            "Notification": "알림",
            "notification": "알림",
            "Alert": "경고",
            "alert": "경고",
            "Warning": "경고",
            "warning": "경고",
            "Hint": "힌트",
            "hint": "힌트",
            "Tooltip": "툴팁",
            "tooltip": "툴팁",
            "Description": "설명",
            "description": "설명",
            "Comment": "주석",
            "comment": "주석",
            "Note": "메모",
            "note": "메모",
            "Label": "레이블",
            "label": "레이블",
            "Title": "제목",
            "title": "제목",
            "Name": "이름",
            "name": "이름",
            "Identifier": "식별자",
            "identifier": "식별자",
            "ID": "ID",
            "Signature": "서명",
            "signature": "서명",
            "Format": "형식",
            "Encoding": "인코딩",
            "encoding": "인코딩",
            "Charset": "문자 집합",
            "charset": "문자 집합",
            "Language": "언어",
            "language": "언어",
            "Locale": "로케일",
            "locale": "로케일",
            "Region": "지역",
            "region": "지역",
            "Country": "국가",
            "country": "국가",
            "Zone": "구역",
            "zone": "구역",
            "Platform": "플랫폼",
            "platform": "플랫폼",
            "System": "시스템",
            "system": "시스템",
            "Environment": "환경",
            "environment": "환경",
            "Context": "컨텍스트",
            "context": "컨텍스트",
            "Scope": "범위",
            "scope": "범위",
            "Target": "대상",
            "target": "대상",
            "Source": "소스",
            "source": "소스",
            "Destination": "대상",
            "destination": "대상",
            "Origin": "원본",
            "origin": "원본",
            "Reference": "참조",
            "reference": "참조",
            "Link": "링크",
            "link": "링크",
            "Dependency": "종속성",
            "dependency": "종속성",
            "Relation": "관계",
            "relation": "관계",
            "Mapping": "매핑",
            "mapping": "매핑",
            "Binding": "바인딩",
            "binding": "바인딩",
            "Association": "연결",
            "association": "연결",
            "Attachment": "첨부 파일",
            "attachment": "첨부 파일",
            "Extension": "확장",
            "extension": "확장",
            "Plugin": "플러그인",
            "plugin": "플러그인",
            "Addon": "애드온",
            "addon": "애드온",
            "Component": "컴포넌트",
            "component": "컴포넌트",
            "Widget": "위젯",
            "widget": "위젯",
            "Control": "컨트롤",
            "control": "컨트롤",
            "Button": "버튼",
            "button": "버튼",
            "Checkbox": "체크박스",
            "checkbox": "체크박스",
            "Radio": "라디오",
            "radio": "라디오",
            "Dropdown": "드롭다운",
            "dropdown": "드롭다운",
            "Combobox": "콤보박스",
            "combobox": "콤보박스",
            "Textbox": "텍스트 상자",
            "textbox": "텍스트 상자",
            "Input": "입력",
            "input": "입력",
            "Output": "출력",
            "output": "출력",
            "Stream": "스트림",
            "stream": "스트림",
            "Buffer": "버퍼",
            "buffer": "버퍼",
            "Cache": "캐시",
            "cache": "캐시",
            "Memory": "메모리",
            "memory": "메모리",
            "Storage": "저장소",
            "storage": "저장소",
            "Database": "데이터베이스",
            "database": "데이터베이스",
            "Schema": "스키마",
            "schema": "스키마",
            "Query": "쿼리",
            "query": "쿼리",
            "Transaction": "트랜잭션",
            "transaction": "트랜잭션",
            "Cursor": "커서",
            "cursor": "커서",
            "Pointer": "포인터",
            "pointer": "포인터",
            "Address": "주소",
            "address": "주소",
            "Register": "레지스터",
            "register": "레지스터",
            "Flag": "플래그",
            "flag": "플래그",
            "Bit": "비트",
            "bit": "비트",
            "Byte": "바이트",
            "byte": "바이트",
            "Word": "워드",
            "word": "워드",
            "Integer": "정수",
            "integer": "정수",
            "Float": "부동 소수점",
            "float": "부동 소수점",
            "Double": "배정도",
            "double": "배정도",
            "Decimal": "십진수",
            "decimal": "십진수",
            "Boolean": "부울",
            "boolean": "부울",
            "Character": "문자",
            "character": "문자",
            "String": "문자열",
            "string": "문자열",
            "Array": "배열",
            "array": "배열",
            "Vector": "벡터",
            "vector": "벡터",
            "Matrix": "행렬",
            "matrix": "행렬",
            "Object": "객체",
            "object": "객체",
            "Instance": "인스턴스",
            "instance": "인스턴스",
            "Structure": "구조체",
            "structure": "구조체",
            "Union": "공용체",
            "union": "공용체",
            "Enum": "열거형",
            "enum": "열거형",
            "Constant": "상수",
            "constant": "상수",
            "Literal": "리터럴",
            "literal": "리터럴",
            "Operator": "연산자",
            "operator": "연산자",
            "Statement": "문",
            "statement": "문",
            "Block": "블록",
            "block": "블록",
            "Clause": "절",
            "clause": "절",
            "Condition": "조건",
            "condition": "조건",
            "Loop": "루프",
            "loop": "루프",
            "Iteration": "반복",
            "iteration": "반복",
            "Recursion": "재귀",
            "recursion": "재귀",
            "Exception": "예외",
            "exception": "예외",
            "Throw": "던지기",
            "throw": "던지기",
            "Catch": "잡기",
            "catch": "잡기",
            "Finally": "마지막으로",
            "finally": "마지막으로",
            "Try": "시도",
            "try": "시도",
            "Return": "반환",
            "return": "반환",
            "Yield": "산출",
            "yield": "산출",
            "Import": "가져오기",
            "import": "가져오기",
            "Export": "내보내기",
            "export": "내보내기",
            "Include": "포함",
            "include": "포함",
            "Require": "요구",
            "require": "요구",
            "Inherit": "상속",
            "inherit": "상속",
            "Extend": "확장",
            "extend": "확장",
            "Implement": "구현",
            "implement": "구현",
            "Override": "재정의",
            "override": "재정의",
            "Overload": "오버로드",
            "overload": "오버로드",
            "Abstract": "추상",
            "abstract": "추상",
            "Virtual": "가상",
            "virtual": "가상",
            "Static": "정적",
            "static": "정적",
            "Final": "최종",
            "final": "최종",
            "Public": "공개",
            "public": "공개",
            "Private": "비공개",
            "private": "비공개",
            "Protected": "보호됨",
            "protected": "보호됨",
            "Internal": "내부",
            "internal": "내부",
            "External": "외부",
            "external": "외부",
            "Global": "전역",
            "global": "전역",
            "Local": "지역",
            "local": "지역",
            "Volatile": "휘발성",
            "volatile": "휘발성",
            "Mutable": "변경 가능",
            "mutable": "변경 가능",
            "Immutable": "불변",
            "immutable": "불변",
            "Readonly": "읽기 전용",
            "readonly": "읽기 전용",
            "Writeonly": "쓰기 전용",
            "writeonly": "쓰기 전용",
            "Nullable": "null 허용",
            "nullable": "null 허용",
            "Optional": "선택 사항",
            "optional": "선택 사항",
            "Required": "필수",
            "required": "필수",
            "Mandatory": "필수",
            "mandatory": "필수",
            "Deprecated": "사용되지 않음",
            "deprecated": "사용되지 않음",
            "Obsolete": "더 이상 사용되지 않음",
            "obsolete": "더 이상 사용되지 않음",
            "Legacy": "레거시",
            "legacy": "레거시",
            "Experimental": "실험적",
            "experimental": "실험적",
            "Beta": "베타",
            "beta": "베타",
            "Alpha": "알파",
            "alpha": "알파",
            "Stable": "안정",
            "stable": "안정",
            "Release": "릴리스",
            "release": "릴리스",
            "Snapshot": "스냅샷",
            "snapshot": "스냅샷",
            "Milestone": "마일스톤",
            "milestone": "마일스톤",
            "Candidate": "후보",
            "candidate": "후보",
            "Production": "프로덕션",
            "production": "프로덕션",
            "Development": "개발",
            "development": "개발",
            "Testing": "테스트",
            "testing": "테스트",
            "Staging": "스테이징",
            "staging": "스테이징",
            "Preview": "미리보기",
            "preview": "미리보기",
            "Prototype": "프로토타입",
            "prototype": "프로토타입",
            "Demo": "데모",
            "demo": "데모",
            "Sample": "샘플",
            "sample": "샘플",
            "Example": "예제",
            "example": "예제",
            "Benchmark": "벤치마크",
            "benchmark": "벤치마크",
            "Test": "테스트",
            "test": "테스트",
            "Unit": "단위",
            "unit": "단위",
            "Integration": "통합",
            "integration": "통합",
            "Functional": "기능",
            "functional": "기능",
            "Performance": "성능",
            "performance": "성능",
            "Load": "로드",
            "load": "로드",
            "Stress": "스트레스",
            "stress": "스트레스",
            "Volume": "볼륨",
            "volume": "볼륨",
            "Regression": "회귀",
            "regression": "회귀",
            "Smoke": "스모크",
            "smoke": "스모크",
            "Sanity": "정상 작동 여부",
            "sanity": "정상 작동 여부",
            "Acceptance": "수락",
            "acceptance": "수락",
            "Coverage": "커버리지",
            "coverage": "커버리지",
            "Report": "보고서",
            "report": "보고서",
            "Log": "로그",
            "log": "로그",
            "Trace": "추적",
            "trace": "추적",
            "Debug": "디버그",
            "debug": "디버그",
            "Info": "정보",
            "info": "정보",
            "Warn": "경고",
            "warn": "경고",
            "Fatal": "치명적",
            "fatal": "치명적",
            "Critical": "중요",
            "critical": "중요",
            "High": "높음",
            "high": "높음",
            "Medium": "보통",
            "medium": "보통",
            "Low": "낮음",
            "low": "낮음",
            "Verbose": "자세함",
            "verbose": "자세함",
            "Quiet": "조용함",
            "quiet": "조용함",
            "Silent": "무음",
            "silent": "무음",
            "Normal": "보통",
            "normal": "보통",
            "Detailed": "상세",
            "detailed": "상세",
            "Summary": "요약",
            "summary": "요약",
            "Brief": "간략",
            "brief": "간략",
            "Full": "전체",
            "full": "전체",
            "Partial": "부분",
            "partial": "부분",
            "Complete": "완료",
            "complete": "완료",
            "Incomplete": "미완료",
            "incomplete": "미완료",
            "Pending": "보류 중",
            "pending": "보류 중",
            "Active": "활성",
            "active": "활성",
            "Inactive": "비활성",
            "inactive": "비활성",
            "Enabled": "사용",
            "enabled": "사용",
            "Disabled": "사용 안 함",
            "disabled": "사용 안 함",
            "On": "켜기",
            "on": "켜기",
            "Off": "끄기",
            "off": "끄기",
            "True": "참",
            "true": "참",
            "False": "거짓",
            "false": "거짓",
            "Yes": "예",
            "yes": "예",
            "No": "아니요",
            "no": "아니요",
            "OK": "확인",
            "ok": "확인",
            "Cancel": "취소",
            "cancel": "취소",
            "Apply": "적용",
            "apply": "적용",
            "Reset": "재설정",
            "reset": "재설정",
            "Restore": "복원",
            "restore": "복원",
            "Reload": "다시 로드",
            "reload": "다시 로드",
            "Refresh": "새로 고침",
            "refresh": "새로 고침",
            "Clear": "지우기",
            "clear": "지우기",
            "Clean": "정리",
            "clean": "정리",
            "Remove": "제거",
            "remove": "제거",
            "Add": "추가",
            "add": "추가",
            "Insert": "삽입",
            "insert": "삽입",
            "Append": "추가",
            "append": "추가",
            "Prepend": "앞에 추가",
            "prepend": "앞에 추가",
            "Move": "이동",
            "move": "이동",
            "Shift": "이동",
            "shift": "이동",
            "Swap": "교환",
            "swap": "교환",
            "Exchange": "교환",
            "exchange": "교환",
            "Convert": "변환",
            "convert": "변환",
            "Transform": "변형",
            "transform": "변형",
            "Translate": "번역",
            "translate": "번역",
            "Encode": "인코딩",
            "encode": "인코딩",
            "Decode": "디코딩",
            "decode": "디코딩",
            "Compress": "압축",
            "compress": "압축",
            "Decompress": "압축 해제",
            "decompress": "압축 해제",
            "Zip": "압축",
            "zip": "압축",
            "Unzip": "압축 해제",
            "unzip": "압축 해제",
            "Archive": "아카이브",
            "archive": "아카이브",
            "Extract": "추출",
            "extract": "추출",
            "Pack": "묶기",
            "pack": "묶기",
            "Unpack": "풀기",
            "unpack": "풀기",
            "Download": "다운로드",
            "download": "다운로드",
            "Upload": "업로드",
            "upload": "업로드",
            "Sync": "동기화",
            "sync": "동기화",
            "Synchronize": "동기화",
            "synchronize": "동기화",
            "Backup": "백업",
            "backup": "백업",
            "Recovery": "복구",
            "recovery": "복구",
            "Migrate": "마이그레이션",
            "migrate": "마이그레이션",
            "Upgrade": "업그레이드",
            "upgrade": "업그레이드",
            "Downgrade": "다운그레이드",
            "downgrade": "다운그레이드",
            "Rollback": "롤백",
            "rollback": "롤백",
            "Revert": "되돌리기",
            "revert": "되돌리기",
            "Undo": "실행 취소",
            "undo": "실행 취소",
            "Redo": "다시 실행",
            "redo": "다시 실행",
            "Repeat": "반복",
            "repeat": "반복",
            "Retry": "다시 시도",
            "retry": "다시 시도",
            "Resume": "다시 시작",
            "resume": "다시 시작",
            "Pause": "일시 중지",
            "pause": "일시 중지",
            "Stop": "중지",
            "stop": "중지",
            "Start": "시작",
            "start": "시작",
            "Restart": "다시 시작",
            "restart": "다시 시작",
            "Shutdown": "종료",
            "shutdown": "종료",
            "Terminate": "종료",
            "terminate": "종료",
            "Kill": "강제 종료",
            "kill": "강제 종료",
            "Abort": "중단",
            "abort": "중단",
            "Exit": "종료",
            "exit": "종료",
            "Quit": "종료",
            "quit": "종료",
            "Close": "닫기",
            "close": "닫기",
            "Open": "열기",
            "open": "열기",
            "Show": "표시",
            "show": "표시",
            "Hide": "숨기기",
            "hide": "숨기기",
            "Toggle": "전환",
            "toggle": "전환",
            "Switch": "전환",
            "switch": "전환",
            "Change": "변경",
            "change": "변경",
            "Modify": "수정",
            "modify": "수정",
            "Adjust": "조정",
            "adjust": "조정",
            "Tune": "조정",
            "tune": "조정",
            "Customize": "사용자 지정",
            "customize": "사용자 지정",
            "Personalize": "개인 설정",
            "personalize": "개인 설정",
            "Configure": "구성",
            "configure": "구성",
            "Setup": "설정",
            "setup": "설정",
            "Initialize": "초기화",
            "initialize": "초기화",
            "Prepare": "준비",
            "prepare": "준비",
            "Process": "처리",
            "Validate": "유효성 검사",
            "validate": "유효성 검사",
            "Verify": "확인",
            "verify": "확인",
            "Check": "확인",
            "check": "확인",
            "Inspect": "검사",
            "inspect": "검사",
            "Examine": "조사",
            "examine": "조사",
            "Review": "검토",
            "review": "검토",
            "Audit": "감사",
            "audit": "감사",
            "Monitor": "모니터링",
            "monitor": "모니터링",
            "Watch": "감시",
            "watch": "감시",
            "Observe": "관찰",
            "observe": "관찰",
            "Track": "추적",
            "track": "추적",
            "Record": "기록",
            "Capture": "캡처",
            "capture": "캡처",
            "Snapshot": "스냅샷",
            "Screenshot": "스크린샷",
            "screenshot": "스크린샷",
            "Print": "인쇄",
            "print": "인쇄",
            "Export": "내보내기",
            "Import": "가져오기",
            "Send": "보내기",
            "send": "보내기",
            "Receive": "받기",
            "receive": "받기",
            "Transmit": "전송",
            "transmit": "전송",
            "Broadcast": "브로드캐스트",
            "broadcast": "브로드캐스트",
            "Publish": "게시",
            "publish": "게시",
            "Subscribe": "구독",
            "subscribe": "구독",
            "Notify": "알림",
            "notify": "알림",
            "Inform": "알림",
            "inform": "알림",
            "Announce": "알림",
            "announce": "알림",
            "Declare": "선언",
            "declare": "선언",
            "Define": "정의",
            "define": "정의",
            "Specify": "지정",
            "specify": "지정",
            "Describe": "설명",
            "describe": "설명",
            "Explain": "설명",
            "explain": "설명",
            "Clarify": "명확히",
            "clarify": "명확히",
            "Illustrate": "예시",
            "illustrate": "예시",
            "Demonstrate": "시연",
            "demonstrate": "시연",
            "Present": "제시",
            "present": "제시",
            "Display": "표시",
            "display": "표시",
            "Render": "렌더링",
            "render": "렌더링",
            "Draw": "그리기",
            "draw": "그리기",
            "Paint": "페인트",
            "paint": "페인트",
            "Fill": "채우기",
            "fill": "채우기",
            "Stroke": "스트로크",
            "stroke": "스트로크",
            "Outline": "윤곽선",
            "outline": "윤곽선",
            "Border": "테두리",
            "border": "테두리",
            "Edge": "가장자리",
            "edge": "가장자리",
            "Corner": "모서리",
            "corner": "모서리",
            "Center": "중앙",
            "center": "중앙",
            "Middle": "중간",
            "middle": "중간",
            "Top": "위",
            "top": "위",
            "Bottom": "아래",
            "bottom": "아래",
            "Left": "왼쪽",
            "left": "왼쪽",
            "Right": "오른쪽",
            "right": "오른쪽",
            "Start": "시작",
            "End": "끝",
            "end": "끝",
            "Begin": "시작",
            "begin": "시작",
            "Finish": "완료",
            "finish": "완료",
            "First": "첫 번째",
            "first": "첫 번째",
            "Last": "마지막",
            "last": "마지막",
            "Next": "다음",
            "next": "다음",
            "Previous": "이전",
            "previous": "이전",
            "Forward": "앞으로",
            "forward": "앞으로",
            "Backward": "뒤로",
            "backward": "뒤로",
            "Up": "위로",
            "up": "위로",
            "Down": "아래로",
            "down": "아래로",
            "Horizontal": "가로",
            "horizontal": "가로",
            "Vertical": "세로",
            "vertical": "세로",
            "Diagonal": "대각선",
            "diagonal": "대각선",
            "Parallel": "평행",
            "parallel": "평행",
            "Perpendicular": "수직",
            "perpendicular": "수직",
            "Angle": "각도",
            "angle": "각도",
            "Rotation": "회전",
            "rotation": "회전",
            "Rotate": "회전",
            "rotate": "회전",
            "Flip": "뒤집기",
            "flip": "뒤집기",
            "Mirror": "미러",
            "mirror": "미러",
            "Invert": "반전",
            "invert": "반전",
            "Reverse": "역순",
            "reverse": "역순",
            "Sort": "정렬",
            "sort": "정렬",
            "Order": "순서",
            "order": "순서",
            "Arrange": "정렬",
            "arrange": "정렬",
            "Organize": "구성",
            "organize": "구성",
            "Group": "그룹",
            "group": "그룹",
            "Ungroup": "그룹 해제",
            "ungroup": "그룹 해제",
            "Merge": "병합",
            "Split": "분할",
            "split": "분할",
            "Divide": "나누기",
            "divide": "나누기",
            "Separate": "분리",
            "separate": "분리",
            "Combine": "결합",
            "combine": "결합",
            "Join": "조인",
            "join": "조인",
            "Connect": "연결",
            "connect": "연결",
            "Disconnect": "연결 해제",
            "disconnect": "연결 해제",
            "Attach": "연결",
            "attach": "연결",
            "Detach": "분리",
            "detach": "분리",
            "Link": "링크",
            "Unlink": "링크 해제",
            "unlink": "링크 해제",
            "Bind": "바인딩",
            "bind": "바인딩",
            "Unbind": "바인딩 해제",
            "unbind": "바인딩 해제",
            "Associate": "연결",
            "associate": "연결",
            "Disassociate": "연결 해제",
            "disassociate": "연결 해제",
            "Couple": "연결",
            "couple": "연결",
            "Decouple": "분리",
            "decouple": "분리",
            "Pair": "쌍",
            "pair": "쌍",
            "Unpair": "쌍 해제",
            "unpair": "쌍 해제",
            "Match": "일치",
            "match": "일치",
            "Compare": "비교",
            "compare": "비교",
            "Diff": "차이",
            "diff": "차이",
            "Difference": "차이",
            "difference": "차이",
            "Similarity": "유사성",
            "similarity": "유사성",
            "Equal": "같음",
            "equal": "같음",
            "Equivalent": "동등",
            "equivalent": "동등",
            "Identical": "동일",
            "identical": "동일",
            "Same": "같음",
            "same": "같음",
            "Different": "다름",
            "different": "다름",
            "Distinct": "구별됨",
            "distinct": "구별됨",
            "Unique": "고유",
            "unique": "고유",
            "Duplicate": "복제",
            "duplicate": "복제",
            "Clone": "복제",
            "clone": "복제",
            "Replicate": "복제",
            "replicate": "복제",
            "Reproduce": "재현",
            "reproduce": "재현",
            "Recreate": "다시 생성",
            "recreate": "다시 생성",
            "Regenerate": "재생성",
            "regenerate": "재생성",
            "Rebuild": "다시 빌드",
            "rebuild": "다시 빌드",
            "Recompile": "다시 컴파일",
            "recompile": "다시 컴파일",
            "Reinstall": "다시 설치",
            "reinstall": "다시 설치",
            "Uninstall": "제거",
            "uninstall": "제거",
            "Deploy": "배포",
            "deploy": "배포",
            "Undeploy": "배포 취소",
            "undeploy": "배포 취소",
            "Launch": "시작",
            "launch": "시작",
            "Run": "실행",
            "run": "실행",
            "Execute": "실행",
            "execute": "실행",
            "Invoke": "호출",
            "invoke": "호출",
            "Call": "호출",
            "call": "호출",
            "Trigger": "트리거",
            "trigger": "트리거",
            "Fire": "발생",
            "fire": "발생",
            "Emit": "발생",
            "emit": "발생",
            "Raise": "발생",
            "raise": "발생",
            "Dispatch": "전달",
            "dispatch": "전달",
            "Handle": "처리",
            "handle": "처리",
            "Manage": "관리",
            "manage": "관리",
            "Control": "제어",
            "Coordinate": "조정",
            "coordinate": "조정",
            "Orchestrate": "오케스트레이션",
            "orchestrate": "오케스트레이션",
            "Schedule": "예약",
            "schedule": "예약",
            "Queue": "대기열",
            "queue": "대기열",
            "Enqueue": "대기열 추가",
            "enqueue": "대기열 추가",
            "Dequeue": "대기열 제거",
            "dequeue": "대기열 제거",
            "Push": "푸시",
            "push": "푸시",
            "Pop": "팝",
            "pop": "팝",
            "Peek": "엿보기",
            "peek": "엿보기",
            "Poll": "폴링",
            "poll": "폴링",
            "Wait": "대기",
            "wait": "대기",
            "Sleep": "대기",
            "sleep": "대기",
            "Delay": "지연",
            "delay": "지연",
            "Defer": "연기",
            "defer": "연기",
            "Postpone": "연기",
            "postpone": "연기",
            "Skip": "건너뛰기",
            "skip": "건너뛰기",
            "Ignore": "무시",
            "ignore": "무시",
            "Discard": "삭제",
            "discard": "삭제",
            "Reject": "거부",
            "reject": "거부",
            "Deny": "거부",
            "deny": "거부",
            "Block": "차단",
            "Unblock": "차단 해제",
            "unblock": "차단 해제",
            "Allow": "허용",
            "allow": "허용",
            "Permit": "허용",
            "permit": "허용",
            "Grant": "부여",
            "grant": "부여",
            "Revoke": "취소",
            "revoke": "취소",
            "Approve": "승인",
            "approve": "승인",
            "Disapprove": "거부",
            "disapprove": "거부",
            "Accept": "수락",
            "accept": "수락",
            "Decline": "거부",
            "decline": "거부",
            "Confirm": "확인",
            "confirm": "확인",
            "Acknowledge": "확인",
            "acknowledge": "확인",
            "Recognize": "인식",
            "recognize": "인식",
            "Identify": "식별",
            "identify": "식별",
            "Detect": "감지",
            "detect": "감지",
            "Discover": "발견",
            "discover": "발견",
            "Locate": "찾기",
            "locate": "찾기",
            "Determine": "결정",
            "determine": "결정",
            "Calculate": "계산",
            "calculate": "계산",
            "Compute": "계산",
            "compute": "계산",
            "Evaluate": "평가",
            "evaluate": "평가",
            "Measure": "측정",
            "measure": "측정",
            "Estimate": "추정",
            "estimate": "추정",
            "Predict": "예측",
            "predict": "예측",
            "Forecast": "예측",
            "forecast": "예측",
            "Analyze": "분석",
            "analyze": "분석",
            "Profile": "프로파일",
            "profile": "프로파일",
            "Diagnose": "진단",
            "diagnose": "진단",
            "Troubleshoot": "문제 해결",
            "troubleshoot": "문제 해결",
            "Fix": "수정",
            "fix": "수정",
            "Repair": "수리",
            "repair": "수리",
            "Correct": "수정",
            "correct": "수정",
            "Improve": "개선",
            "improve": "개선",
            "Enhance": "향상",
            "enhance": "향상",
            "Augment": "증강",
            "augment": "증강",
            "Enrich": "강화",
            "enrich": "강화",
            "Strengthen": "강화",
            "strengthen": "강화",
            "Weaken": "약화",
            "weaken": "약화",
            "Reduce": "줄이기",
            "reduce": "줄이기",
            "Increase": "늘리기",
            "increase": "늘리기",
            "Expand": "확장",
            "expand": "확장",
            "Collapse": "축소",
            "collapse": "축소",
            "Shrink": "축소",
            "shrink": "축소",
            "Grow": "증가",
            "grow": "증가",
            "Decrease": "감소",
            "decrease": "감소",
            "Minimize": "최소화",
            "minimize": "최소화",
            "Maximize": "최대화",
            "maximize": "최대화",
            "Normalize": "정규화",
            "normalize": "정규화",
            "Standardize": "표준화",
            "standardize": "표준화",
            "Regularize": "정규화",
            "regularize": "정규화",
            "Simplify": "단순화",
            "simplify": "단순화",
            "Complicate": "복잡하게",
            "complicate": "복잡하게",
            "Aggregate": "집계",
            "aggregate": "집계",
            "Accumulate": "누적",
            "accumulate": "누적",
            "Collect": "수집",
            "collect": "수집",
            "Gather": "수집",
            "gather": "수집",
            "Assemble": "조립",
            "assemble": "조립",
            "Compile": "컴파일",
            "compile": "컴파일",
            "Synthesize": "합성",
            "synthesize": "합성",
            "Compose": "작성",
            "compose": "작성",
            "Construct": "구성",
            "construct": "구성",
            "Build": "빌드",
            "build": "빌드",
            "Make": "만들기",
            "make": "만들기",
            "Fabricate": "제작",
            "fabricate": "제작",
            "Manufacture": "제조",
            "manufacture": "제조",
            "Produce": "생성",
            "produce": "생성",
            "Create": "생성",
            "create": "생성",
            "Destroy": "파괴",
            "destroy": "파괴",
            "Demolish": "철거",
            "demolish": "철거",
            "Erase": "지우기",
            "erase": "지우기",
            "Wipe": "삭제",
            "wipe": "삭제",
            "Purge": "제거",
            "purge": "제거",
            "Flush": "플러시",
            "flush": "플러시",
            "Drain": "비우기",
            "drain": "비우기",
            "Empty": "비우기",
            "empty": "비우기",
            "Blank": "비어 있음",
            "blank": "비어 있음",
            "Null": "null",
            "null": "null",
            "Nil": "nil",
            "nil": "nil",
            "None": "없음",
            "none": "없음",
            "Nothing": "없음",
            "nothing": "없음",
            "Zero": "0",
            "zero": "0",
            "One": "1",
            "one": "1",
            "Many": "많음",
            "many": "많음",
            "Multiple": "여러 개",
            "multiple": "여러 개",
            "Single": "단일",
            "single": "단일",
            "All": "모두",
            "all": "모두",
            "Any": "임의",
            "any": "임의",
            "Some": "일부",
            "some": "일부",
            "Few": "몇 개",
            "few": "몇 개",
            "Several": "여러 개",
            "several": "여러 개",
            "Other": "기타",
            "other": "기타",
            "Another": "다른",
            "another": "다른",
            "Else": "그 외",
            "else": "그 외",
            "Otherwise": "그 외",
            "otherwise": "그 외",
            "Alternative": "대안",
            "alternative": "대안",
            "Fallback": "대체",
            "fallback": "대체",
            "Default": "기본",
            "Custom": "사용자 지정",
            "custom": "사용자 지정",
            "User": "사용자",
            "user": "사용자",
            "System": "시스템",
            "General": "일반",
            "general": "일반",
            "Specific": "특정",
            "specific": "특정",
            "Generic": "일반",
            "generic": "일반",
            "Special": "특수",
            "special": "특수",
            "Common": "공통",
            "common": "공통",
            "Standard": "표준",
            "standard": "표준",
            "Advanced": "고급",
            "advanced": "고급",
            "Basic": "기본",
            "basic": "기본",
            "Simple": "단순",
            "simple": "단순",
            "Complex": "복합",
            "complex": "복합",
            "Easy": "쉬움",
            "easy": "쉬움",
            "Hard": "어려움",
            "hard": "어려움",
            "Difficult": "어려움",
            "difficult": "어려움",
            "Quick": "빠름",
            "quick": "빠름",
            "Fast": "빠름",
            "fast": "빠름",
            "Slow": "느림",
            "slow": "느림",
            "Rapid": "빠름",
            "rapid": "빠름",
            "Instant": "즉시",
            "instant": "즉시",
            "Immediate": "즉시",
            "immediate": "즉시",
            "Delayed": "지연됨",
            "delayed": "지연됨",
            "Asynchronous": "비동기",
            "asynchronous": "비동기",
            "Synchronous": "동기",
            "synchronous": "동기",
            "Async": "비동기",
            "async": "비동기",
            "Blocking": "차단",
            "blocking": "차단",
            "Non-blocking": "비차단",
            "non-blocking": "비차단",
            "Concurrent": "동시",
            "concurrent": "동시",
            "Sequential": "순차",
            "sequential": "순차",
            "Serial": "직렬",
            "serial": "직렬",
            "Ordered": "순서가 있는",
            "ordered": "순서가 있는",
            "Unordered": "순서가 없는",
            "unordered": "순서가 없는",
            "Random": "무작위",
            "random": "무작위",
            "Deterministic": "결정적",
            "deterministic": "결정적",
            "Predictable": "예측 가능",
            "predictable": "예측 가능",
            "Unpredictable": "예측 불가능",
            "unpredictable": "예측 불가능",
            "Reliable": "신뢰할 수 있는",
            "reliable": "신뢰할 수 있는",
            "Unreliable": "신뢰할 수 없는",
            "unreliable": "신뢰할 수 없는",
            "Consistent": "일관된",
            "consistent": "일관된",
            "Inconsistent": "일관되지 않은",
            "inconsistent": "일관되지 않은",
            "Stable": "안정",
            "Unstable": "불안정",
            "unstable": "불안정",
            "Robust": "견고한",
            "robust": "견고한",
            "Fragile": "취약한",
            "fragile": "취약한",
            "Secure": "보안",
            "secure": "보안",
            "Insecure": "비보안",
            "insecure": "비보안",
            "Safe": "안전",
            "safe": "안전",
            "Unsafe": "안전하지 않음",
            "unsafe": "안전하지 않음",
            "Dangerous": "위험",
            "dangerous": "위험",
            "Risky": "위험",
            "risky": "위험",
            "Trusted": "신뢰됨",
            "trusted": "신뢰됨",
            "Untrusted": "신뢰되지 않음",
            "untrusted": "신뢰되지 않음",
            "Verified": "확인됨",
            "verified": "확인됨",
            "Unverified": "확인되지 않음",
            "unverified": "확인되지 않음",
            "Certified": "인증됨",
            "certified": "인증됨",
            "Uncertified": "인증되지 않음",
            "uncertified": "인증되지 않음",
            "Signed": "서명됨",
            "signed": "서명됨",
            "Unsigned": "서명되지 않음",
            "unsigned": "서명되지 않음",
            "Encrypted": "암호화됨",
            "encrypted": "암호화됨",
            "Decrypted": "해독됨",
            "decrypted": "해독됨",
            "Hashed": "해시됨",
            "hashed": "해시됨",
            "Compressed": "압축됨",
            "compressed": "압축됨",
            "Decompressed": "압축 해제됨",
            "decompressed": "압축 해제됨",
            "Serialized": "직렬화됨",
            "serialized": "직렬화됨",
            "Deserialized": "역직렬화됨",
            "deserialized": "역직렬화됨",
            "Marshalled": "마샬링됨",
            "marshalled": "마샬링됨",
            "Unmarshalled": "언마샬링됨",
            "unmarshalled": "언마샬링됨",
            "Formatted": "형식 지정됨",
            "formatted": "형식 지정됨",
            "Unformatted": "형식 지정되지 않음",
            "unformatted": "형식 지정되지 않음",
            "Wrapped": "래핑됨",
            "wrapped": "래핑됨",
            "Unwrapped": "언래핑됨",
            "unwrapped": "언래핑됨",
            "Boxed": "박싱됨",
            "boxed": "박싱됨",
            "Unboxed": "언박싱됨",
            "unboxed": "언박싱됨",
            "Casted": "캐스팅됨",
            "casted": "캐스팅됨",
            "Converted": "변환됨",
            "converted": "변환됨",
            "Transformed": "변형됨",
            "transformed": "변형됨",
            "Translated": "번역됨",
            "translated": "번역됨",
            "Mapped": "매핑됨",
            "mapped": "매핑됨",
            "Filtered": "필터링됨",
            "filtered": "필터링됨",
            "Sorted": "정렬됨",
            "sorted": "정렬됨",
            "Grouped": "그룹화됨",
            "grouped": "그룹화됨",
            "Merged": "병합됨",
            "merged": "병합됨",
            "Joined": "조인됨",
            "joined": "조인됨",
            "Combined": "결합됨",
            "combined": "결합됨",
            "Concatenated": "연결됨",
            "concatenated": "연결됨",
            "Appended": "추가됨",
            "appended": "추가됨",
            "Prepended": "앞에 추가됨",
            "prepended": "앞에 추가됨",
            "Inserted": "삽입됨",
            "inserted": "삽입됨",
            "Removed": "제거됨",
            "removed": "제거됨",
            "Added": "추가됨",
            "added": "추가됨",
            "Subtracted": "빼기",
            "subtracted": "빼기",
            "Multiplied": "곱하기",
            "multiplied": "곱하기",
            "Divided": "나누기",
            "divided": "나누기",
            "Modulo": "나머지",
            "modulo": "나머지",
            "Incremented": "증가됨",
            "incremented": "증가됨",
            "Decremented": "감소됨",
            "decremented": "감소됨",
            "Negated": "부정됨",
            "negated": "부정됨",
            "Inverted": "반전됨",
            "inverted": "반전됨",
            "Complemented": "보완됨",
            "complemented": "보완됨",
            "Shifted": "이동됨",
            "shifted": "이동됨",
            "Rotated": "회전됨",
            "rotated": "회전됨",
            "Flipped": "뒤집힘",
            "flipped": "뒤집힘",
            "Mirrored": "미러링됨",
            "mirrored": "미러링됨",
            "Reversed": "역순됨",
            "reversed": "역순됨",
            "Truncated": "잘림",
            "truncated": "잘림",
            "Rounded": "반올림됨",
            "rounded": "반올림됨",
            "Floored": "내림됨",
            "floored": "내림됨",
            "Ceiled": "올림됨",
            "ceiled": "올림됨",
            "Clamped": "제한됨",
            "clamped": "제한됨",
            "Saturated": "포화됨",
            "saturated": "포화됨",
            "Normalized": "정규화됨",
            "normalized": "정규화됨",
            "Denormalized": "비정규화됨",
            "denormalized": "비정규화됨",
            "Scaled": "배율 조정됨",
            "scaled": "배율 조정됨",
            "Resized": "크기 조정됨",
            "resized": "크기 조정됨",
            "Cropped": "잘림",
            "cropped": "잘림",
            "Padded": "패딩됨",
            "padded": "패딩됨",
            "Trimmed": "트리밍됨",
            "trimmed": "트리밍됨",
            "Stripped": "제거됨",
            "stripped": "제거됨",
            "Replaced": "교체됨",
            "replaced": "교체됨",
            "Substituted": "대체됨",
            "substituted": "대체됨",
            "Swapped": "교환됨",
            "swapped": "교환됨",
            "Exchanged": "교환됨",
            "exchanged": "교환됨",
            "Switched": "전환됨",
            "switched": "전환됨",
            "Toggled": "전환됨",
            "toggled": "전환됨",
            "Changed": "변경됨",
            "changed": "변경됨",
            "Modified": "수정됨",
            "modified": "수정됨",
            "Altered": "변경됨",
            "altered": "변경됨",
            "Adjusted": "조정됨",
            "adjusted": "조정됨",
            "Tuned": "조정됨",
            "tuned": "조정됨",
            "Calibrated": "보정됨",
            "calibrated": "보정됨",
            "Aligned": "정렬됨",
            "aligned": "정렬됨",
            "Misaligned": "정렬되지 않음",
            "misaligned": "정렬되지 않음",
            "Balanced": "균형됨",
            "balanced": "균형됨",
            "Unbalanced": "불균형됨",
            "unbalanced": "불균형됨",
            "Symmetrical": "대칭",
            "symmetrical": "대칭",
            "Asymmetrical": "비대칭",
            "asymmetrical": "비대칭",
            "Even": "짝수",
            "even": "짝수",
            "Odd": "홀수",
            "odd": "홀수",
            "Positive": "양수",
            "positive": "양수",
            "Negative": "음수",
            "negative": "음수",
            "Absolute": "절대",
            "absolute": "절대",
            "Relative": "상대",
            "relative": "상대",
            "Fixed": "고정",
            "fixed": "고정",
            "Dynamic": "동적",
            "dynamic": "동적",
            "Flexible": "유연",
            "flexible": "유연",
            "Rigid": "경직",
            "rigid": "경직",
            "Elastic": "탄력적",
            "elastic": "탄력적",
            "Adaptive": "적응",
            "adaptive": "적응",
            "Responsive": "반응형",
            "responsive": "반응형",
            "Interactive": "상호작용",
            "interactive": "상호작용",
            "Passive": "수동",
            "passive": "수동",
            "Reactive": "반응형",
            "reactive": "반응형",
            "Proactive": "사전 대응",
            "proactive": "사전 대응",
            "Automatic": "자동",
            "automatic": "자동",
            "Manual": "수동",
            "manual": "수동",
            "Semi-automatic": "반자동",
            "semi-automatic": "반자동",
            "Autonomous": "자율",
            "autonomous": "자율",
            "Independent": "독립",
            "independent": "독립",
            "Dependent": "종속",
            "dependent": "종속",
            "Standalone": "독립 실행형",
            "standalone": "독립 실행형",
            "Integrated": "통합",
            "integrated": "통합",
            "Embedded": "임베디드",
            "embedded": "임베디드",
            "Built-in": "내장",
            "built-in": "내장",
            "Native": "네이티브",
            "native": "네이티브",
            "Cross-platform": "크로스 플랫폼",
            "cross-platform": "크로스 플랫폼",
            "Multi-platform": "멀티 플랫폼",
            "multi-platform": "멀티 플랫폼",
            "Portable": "이식 가능",
            "portable": "이식 가능",
            "Stationary": "고정",
            "stationary": "고정",
            "Mobile": "모바일",
            "mobile": "모바일",
            "Desktop": "데스크톱",
            "desktop": "데스크톱",
            "Web": "웹",
            "web": "웹",
            "Cloud": "클라우드",
            "cloud": "클라우드",
            "Local": "로컬",
            "Remote": "원격",
            "remote": "원격",
            "Distributed": "분산",
            "distributed": "분산",
            "Centralized": "중앙 집중",
            "centralized": "중앙 집중",
            "Decentralized": "분산",
            "decentralized": "분산",
            "Federated": "연합",
            "federated": "연합",
            "Clustered": "클러스터",
            "clustered": "클러스터",
            "Replicated": "복제됨",
            "replicated": "복제됨",
            "Mirrored": "미러링됨",
            "Cached": "캐시됨",
            "cached": "캐시됨",
            "Persisted": "유지됨",
            "persisted": "유지됨",
            "Transient": "일시적",
            "transient": "일시적",
            "Temporary": "임시",
            "temporary": "임시",
            "Permanent": "영구",
            "permanent": "영구",
            "Durable": "내구성",
            "durable": "내구성",
            "Ephemeral": "일시적",
            "ephemeral": "일시적",
            "Persistent": "영구적",
            "persistent": "영구적",
            "Stateful": "상태 보존",
            "stateful": "상태 보존",
            "Stateless": "상태 비보존",
            "stateless": "상태 비보존",
            "Immutable": "불변",
            "Mutable": "변경 가능",
            "Constant": "상수",
            "Readonly": "읽기 전용",
            "Writeonly": "쓰기 전용",
            "Readable": "읽을 수 있음",
            "readable": "읽을 수 있음",
            "Writable": "쓸 수 있음",
            "writable": "쓸 수 있음",
            "Executable": "실행 가능",
            "executable": "실행 가능",
            "Searchable": "검색 가능",
            "searchable": "검색 가능",
            "Sortable": "정렬 가능",
            "sortable": "정렬 가능",
            "Filterable": "필터링 가능",
            "filterable": "필터링 가능",
            "Editable": "편집 가능",
            "editable": "편집 가능",
            "Selectable": "선택 가능",
            "selectable": "선택 가능",
            "Clickable": "클릭 가능",
            "clickable": "클릭 가능",
            "Draggable": "드래그 가능",
            "draggable": "드래그 가능",
            "Droppable": "드롭 가능",
            "droppable": "드롭 가능",
            "Resizable": "크기 조정 가능",
            "resizable": "크기 조정 가능",
            "Movable": "이동 가능",
            "movable": "이동 가능",
            "Scrollable": "스크롤 가능",
            "scrollable": "스크롤 가능",
            "Zoomable": "확대/축소 가능",
            "zoomable": "확대/축소 가능",
            "Expandable": "확장 가능",
            "expandable": "확장 가능",
            "Collapsible": "축소 가능",
            "collapsible": "축소 가능",
            "Foldable": "접을 수 있음",
            "foldable": "접을 수 있음",
            "Closable": "닫을 수 있음",
            "closable": "닫을 수 있음",
            "Dismissable": "닫을 수 있음",
            "dismissable": "닫을 수 있음",
            "Cancelable": "취소 가능",
            "cancelable": "취소 가능",
            "Undoable": "실행 취소 가능",
            "undoable": "실행 취소 가능",
            "Redoable": "다시 실행 가능",
            "redoable": "다시 실행 가능",
            "Repeatable": "반복 가능",
            "repeatable": "반복 가능",
            "Resumable": "다시 시작 가능",
            "resumable": "다시 시작 가능",
            "Pausable": "일시 중지 가능",
            "pausable": "일시 중지 가능",
            "Stoppable": "중지 가능",
            "stoppable": "중지 가능",
            "Startable": "시작 가능",
            "startable": "시작 가능",
            "Restartable": "다시 시작 가능",
            "restartable": "다시 시작 가능",
            "Abortable": "중단 가능",
            "abortable": "중단 가능",
            "Retryable": "다시 시도 가능",
            "retryable": "다시 시도 가능",
            "Recoverable": "복구 가능",
            "recoverable": "복구 가능",
            "Reversible": "되돌릴 수 있음",
            "reversible": "되돌릴 수 있음",
            "Irreversible": "되돌릴 수 없음",
            "irreversible": "되돌릴 수 없음",
            "Renewable": "갱신 가능",
            "renewable": "갱신 가능",
            "Reusable": "재사용 가능",
            "reusable": "재사용 가능",
            "Disposable": "일회용",
            "disposable": "일회용",
            "Recyclable": "재활용 가능",
            "recyclable": "재활용 가능",
            "Interruptible": "중단 가능",
            "interruptible": "중단 가능",
            "Suspendable": "일시 중단 가능",
            "suspendable": "일시 중단 가능",
            "Terminable": "종료 가능",
            "terminable": "종료 가능",
            "Killable": "강제 종료 가능",
            "killable": "강제 종료 가능",
            "Debuggable": "디버그 가능",
            "debuggable": "디버그 가능",
            "Testable": "테스트 가능",
            "testable": "테스트 가능",
            "Mockable": "모의 객체 가능",
            "mockable": "모의 객체 가능",
            "Verifiable": "확인 가능",
            "verifiable": "확인 가능",
            "Validatable": "유효성 검사 가능",
            "validatable": "유효성 검사 가능",
            "Comparable": "비교 가능",
            "comparable": "비교 가능",
            "Equatable": "동등 비교 가능",
            "equatable": "동등 비교 가능",
            "Hashable": "해시 가능",
            "hashable": "해시 가능",
            "Cloneable": "복제 가능",
            "cloneable": "복제 가능",
            "Copyable": "복사 가능",
            "copyable": "복사 가능",
            "Serializable": "직렬화 가능",
            "serializable": "직렬화 가능",
            "Deserializable": "역직렬화 가능",
            "deserializable": "역직렬화 가능",
            "Convertible": "변환 가능",
            "convertible": "변환 가능",
            "Transformable": "변형 가능",
            "transformable": "변형 가능",
            "Translatable": "번역 가능",
            "translatable": "번역 가능",
            "Encodable": "인코딩 가능",
            "encodable": "인코딩 가능",
            "Decodable": "디코딩 가능",
            "decodable": "디코딩 가능",
            "Compressible": "압축 가능",
            "compressible": "압축 가능",
            "Decompressible": "압축 해제 가능",
            "decompressible": "압축 해제 가능",
            "Encryptable": "암호화 가능",
            "encryptable": "암호화 가능",
            "Decryptable": "해독 가능",
            "decryptable": "해독 가능",
            "Signable": "서명 가능",
            "signable": "서명 가능",
            "Verifiable": "확인 가능",
            "Authenticatable": "인증 가능",
            "authenticatable": "인증 가능",
            "Authorizable": "권한 부여 가능",
            "authorizable": "권한 부여 가능",
            "Accessible": "액세스 가능",
            "accessible": "액세스 가능",
            "Inaccessible": "액세스 불가능",
            "inaccessible": "액세스 불가능",
            "Available": "사용 가능",
            "available": "사용 가능",
            "Unavailable": "사용할 수 없음",
            "unavailable": "사용할 수 없음",
            "Ready": "준비됨",
            "ready": "준비됨",
            "Busy": "사용 중",
            "busy": "사용 중",
            "Idle": "유휴",
            "idle": "유휴",
            "Online": "온라인",
            "online": "온라인",
            "Offline": "오프라인",
            "offline": "오프라인",
            "Connected": "연결됨",
            "connected": "연결됨",
            "Disconnected": "연결 해제됨",
            "disconnected": "연결 해제됨",
            "Reachable": "도달 가능",
            "reachable": "도달 가능",
            "Unreachable": "도달 불가능",
            "unreachable": "도달 불가능",
            "Responsive": "응답함",
            "Unresponsive": "응답하지 않음",
            "unresponsive": "응답하지 않음",
            "Alive": "활성",
            "alive": "활성",
            "Dead": "비활성",
            "dead": "비활성",
            "Running": "실행 중",
            "running": "실행 중",
            "Stopped": "중지됨",
            "stopped": "중지됨",
            "Started": "시작됨",
            "started": "시작됨",
            "Paused": "일시 중지됨",
            "paused": "일시 중지됨",
            "Resumed": "다시 시작됨",
            "resumed": "다시 시작됨",
            "Suspended": "일시 중단됨",
            "suspended": "일시 중단됨",
            "Terminated": "종료됨",
            "terminated": "종료됨",
            "Killed": "강제 종료됨",
            "killed": "강제 종료됨",
            "Aborted": "중단됨",
            "aborted": "중단됨",
            "Canceled": "취소됨",
            "canceled": "취소됨",
            "Completed": "완료됨",
            "completed": "완료됨",
            "Finished": "완료됨",
            "finished": "완료됨",
            "Success": "성공",
            "success": "성공",
            "Successful": "성공",
            "successful": "성공",
            "Failure": "실패",
            "failure": "실패",
            "Passed": "통과",
            "passed": "통과",
            "Skipped": "건너뜀",
            "skipped": "건너뜀",
            "Ignored": "무시됨",
            "ignored": "무시됨",
            "Pending": "보류 중",
            "In Progress": "진행 중",
            "in progress": "진행 중",
            "Queued": "대기 중",
            "queued": "대기 중",
            "Scheduled": "예약됨",
            "scheduled": "예약됨",
            "Deferred": "연기됨",
            "deferred": "연기됨",
            "Postponed": "연기됨",
            "postponed": "연기됨",
            "Delayed": "지연됨",
            "Expired": "만료됨",
            "expired": "만료됨",
            "Obsolete": "더 이상 사용되지 않음",
            "Deprecated": "사용되지 않음",
            "Outdated": "오래됨",
            "outdated": "오래됨",
            "Stale": "오래됨",
            "stale": "오래됨",
            "Fresh": "최신",
            "fresh": "최신",
            "New": "새로 만들기",
            "new": "새로 만들기",
            "Old": "오래됨",
            "old": "오래됨",
            "Latest": "최신",
            "latest": "최신",
            "Current": "현재",
            "current": "현재",
            "Recent": "최근",
            "recent": "최근",
            "Historical": "기록",
            "historical": "기록",
            "Archived": "아카이브됨",
            "archived": "아카이브됨",
            "Active": "활성",
            "Inactive": "비활성",
            "Locked": "잠김",
            "locked": "잠김",
            "Unlocked": "잠금 해제됨",
            "unlocked": "잠금 해제됨",
            "Frozen": "고정됨",
            "frozen": "고정됨",
            "Pinned": "고정됨",
            "pinned": "고정됨",
            "Unpinned": "고정 해제됨",
            "unpinned": "고정 해제됨",
            "Sticky": "고정",
            "sticky": "고정",
            "Highlighted": "강조 표시됨",
            "highlighted": "강조 표시됨",
            "Selected": "선택됨",
            "selected": "선택됨",
            "Unselected": "선택 해제됨",
            "unselected": "선택 해제됨",
            "Checked": "선택됨",
            "checked": "선택됨",
            "Unchecked": "선택 해제됨",
            "unchecked": "선택 해제됨",
            "Focused": "포커스됨",
            "focused": "포커스됨",
            "Unfocused": "포커스 해제됨",
            "unfocused": "포커스 해제됨",
            "Hovered": "호버됨",
            "hovered": "호버됨",
            "Pressed": "눌림",
            "pressed": "눌림",
            "Released": "놓음",
            "released": "놓음",
            "Dragged": "드래그됨",
            "dragged": "드래그됨",
            "Dropped": "드롭됨",
            "dropped": "드롭됨",
            "Resized": "크기 조정됨",
            "Moved": "이동됨",
            "moved": "이동됨",
            "Scrolled": "스크롤됨",
            "scrolled": "스크롤됨",
            "Zoomed": "확대/축소됨",
            "zoomed": "확대/축소됨",
            "Expanded": "확장됨",
            "expanded": "확장됨",
            "Collapsed": "축소됨",
            "collapsed": "축소됨",
            "Opened": "열림",
            "opened": "열림",
            "Closed": "닫힘",
            "closed": "닫힘",
            "Shown": "표시됨",
            "shown": "표시됨",
            "Hidden": "숨겨짐",
            "hidden": "숨겨짐",
            "Visible": "보임",
            "visible": "보임",
            "Invisible": "보이지 않음",
            "invisible": "보이지 않음",
            "Opaque": "불투명",
            "opaque": "불투명",
            "Transparent": "투명",
            "transparent": "투명",
            "Translucent": "반투명",
            "translucent": "반투명",
            "Solid": "고체",
            "solid": "고체",
            "Dashed": "파선",
            "dashed": "파선",
            "Dotted": "점선",
            "dotted": "점선",
            "Bold": "굵게",
            "bold": "굵게",
            "Italic": "기울임꼴",
            "italic": "기울임꼴",
            "Underline": "밑줄",
            "underline": "밑줄",
            "Strikethrough": "취소선",
            "strikethrough": "취소선",
            "Uppercase": "대문자",
            "uppercase": "대문자",
            "Lowercase": "소문자",
            "lowercase": "소문자",
            "Capitalize": "첫 글자만 대문자",
            "capitalize": "첫 글자만 대문자",
            "Monospace": "고정폭",
            "monospace": "고정폭",
            "Proportional": "가변폭",
            "proportional": "가변폭",
            "Serif": "세리프",
            "serif": "세리프",
            "Sans-serif": "산세리프",
            "sans-serif": "산세리프",
            "Cursive": "필기체",
            "cursive": "필기체",
            "Fantasy": "판타지",
            "fantasy": "판타지",
            "Small": "작게",
            "small": "작게",
            "Medium": "보통",
            "Large": "크게",
            "large": "크게",
            "Extra Small": "매우 작게",
            "extra small": "매우 작게",
            "Extra Large": "매우 크게",
            "extra large": "매우 크게",
            "Tiny": "아주 작게",
            "tiny": "아주 작게",
            "Huge": "아주 크게",
            "huge": "아주 크게",
            "Compact": "간결",
            "compact": "간결",
            "Comfortable": "편안",
            "comfortable": "편안",
            "Spacious": "넓음",
            "spacious": "넓음",
            "Dense": "밀집",
            "dense": "밀집",
            "Sparse": "희소",
            "sparse": "희소",
            "Tight": "좁음",
            "tight": "좁음",
            "Loose": "느슨",
            "loose": "느슨",
            "Narrow": "좁음",
            "narrow": "좁음",
            "Wide": "넓음",
            "wide": "넓음",
            "Tall": "높음",
            "tall": "높음",
            "Short": "낮음",
            "short": "낮음",
            "Thick": "두꺼움",
            "thick": "두꺼움",
            "Thin": "얇음",
            "thin": "얇음",
            "Heavy": "무거움",
            "heavy": "무거움",
            "Light": "가벼움",
            "light": "가벼움",
            "Dark": "어두움",
            "dark": "어두움",
            "Bright": "밝음",
            "bright": "밝음",
            "Dim": "흐림",
            "dim": "흐림",
            "Vivid": "선명",
            "vivid": "선명",
            "Dull": "둔함",
            "dull": "둔함",
            "Sharp": "선명",
            "sharp": "선명",
            "Blurry": "흐림",
            "blurry": "흐림",
            "Clear": "명확",
            "clear": "명확",
            "Unclear": "불명확",
            "unclear": "불명확",
            "Crisp": "선명",
            "crisp": "선명",
            "Fuzzy": "흐릿한",
            "fuzzy": "흐릿한",
            "Smooth": "부드러움",
            "smooth": "부드러움",
            "Rough": "거친",
            "rough": "거친",
            "Flat": "평평",
            "flat": "평평",
            "Curved": "곡선",
            "curved": "곡선",
            "Straight": "직선",
            "straight": "직선",
            "Bent": "구부러짐",
            "bent": "구부러짐",
            "Circular": "원형",
            "circular": "원형",
            "Square": "정사각형",
            "square": "정사각형",
            "Rectangular": "직사각형",
            "rectangular": "직사각형",
            "Triangular": "삼각형",
            "triangular": "삼각형",
            "Polygonal": "다각형",
            "polygonal": "다각형",
            "Elliptical": "타원형",
            "elliptical": "타원형",
            "Oval": "타원",
            "oval": "타원",
            "Round": "둥근",
            "round": "둥근",
            "Rounded": "둥글게",
            "Edgy": "각진",
            "edgy": "각진",
            "Angular": "각진",
            "angular": "각진",
            "Plain": "단순",
            "plain": "단순",
            "Fancy": "화려",
            "fancy": "화려",
            "Decorative": "장식적",
            "decorative": "장식적",
            "Ornamental": "장식적",
            "ornamental": "장식적",
            "Minimalist": "미니멀",
            "minimalist": "미니멀",
            "Maximalist": "맥시멀",
            "maximalist": "맥시멀",
            "Modern": "현대",
            "modern": "현대",
            "Classic": "클래식",
            "classic": "클래식",
            "Vintage": "빈티지",
            "vintage": "빈티지",
            "Retro": "레트로",
            "retro": "레트로",
            "Contemporary": "현대",
            "contemporary": "현대",
            "Traditional": "전통",
            "traditional": "전통",
            "Conventional": "기존",
            "conventional": "기존",
            "Unconventional": "비기존",
            "unconventional": "비기존",
            "Orthodox": "정통",
            "orthodox": "정통",
            "Unorthodox": "비정통",
            "unorthodox": "비정통",
            "Formal": "공식",
            "formal": "공식",
            "Informal": "비공식",
            "informal": "비공식",
            "Casual": "캐주얼",
            "casual": "캐주얼",
            "Professional": "전문",
            "professional": "전문",
            "Amateur": "아마추어",
            "amateur": "아마추어",
            "Expert": "전문가",
            "expert": "전문가",
            "Novice": "초보자",
            "novice": "초보자",
            "Beginner": "초보자",
            "beginner": "초보자",
            "Intermediate": "중급",
            "intermediate": "중급",
            "Senior": "상급",
            "senior": "상급",
            "Junior": "하급",
            "junior": "하급",
            "Master": "마스터",
            "master": "마스터",
            "Apprentice": "견습생",
            "apprentice": "견습생",
            "Student": "학생",
            "student": "학생",
            "Teacher": "교사",
            "teacher": "교사",
            "Instructor": "강사",
            "instructor": "강사",
            "Trainer": "트레이너",
            "trainer": "트레이너",
            "Mentor": "멘토",
            "mentor": "멘토",
            "Coach": "코치",
            "coach": "코치",
            "Guide": "가이드",
            "guide": "가이드",
            "Helper": "도우미",
            "helper": "도우미",
            "Assistant": "도우미",
            "assistant": "도우미",
            "Support": "지원",
            "support": "지원",
            "Help": "도움말",
            "help": "도움말",
            "Documentation": "문서",
            "documentation": "문서",
            "Manual": "설명서",
            "Reference": "참조",
            "Tutorial": "튜토리얼",
            "tutorial": "튜토리얼",
            "Howto": "방법",
            "howto": "방법",
            "FAQ": "FAQ",
            "faq": "FAQ",
            "Glossary": "용어집",
            "glossary": "용어집",
            "Index": "색인",
            "index": "색인",
            "Contents": "목차",
            "contents": "목차",
            "Overview": "개요",
            "overview": "개요",
            "Introduction": "소개",
            "introduction": "소개",
            "Getting Started": "시작하기",
            "getting started": "시작하기",
            "Quick Start": "빠른 시작",
            "quick start": "빠른 시작",
            "Installation": "설치",
            "installation": "설치",
            "Configuration": "구성",
            "Usage": "사용법",
            "usage": "사용법",
            "Examples": "예제",
            "examples": "예제",
            "Samples": "샘플",
            "samples": "샘플",
            "Demos": "데모",
            "demos": "데모",
            "Tutorials": "튜토리얼",
            "tutorials": "튜토리얼",
            "Guides": "가이드",
            "guides": "가이드",
            "Recipes": "레시피",
            "recipes": "레시피",
            "Best Practices": "모범 사례",
            "best practices": "모범 사례",
            "Tips": "팁",
            "tips": "팁",
            "Tricks": "트릭",
            "tricks": "트릭",
            "Hints": "힌트",
            "hints": "힌트",
            "Notes": "메모",
            "notes": "메모",
            "Warnings": "경고",
            "warnings": "경고",
            "Cautions": "주의",
            "cautions": "주의",
            "Dangers": "위험",
            "dangers": "위험",
            "Important": "중요",
            "important": "중요",
            "Notice": "알림",
            "notice": "알림",
            "Attention": "주의",
            "attention": "주의",
            "Remark": "참고",
            "remark": "참고",
            "See Also": "참고 항목",
            "see also": "참고 항목",
            "Related": "관련",
            "related": "관련",
            "More Information": "추가 정보",
            "more information": "추가 정보",
            "Details": "세부 정보",
            "details": "세부 정보",
            "Specification": "사양",
            "specification": "사양",
            "Requirements": "요구 사항",
            "requirements": "요구 사항",
            "Prerequisites": "전제 조건",
            "prerequisites": "전제 조건",
            "Dependencies": "종속성",
            "dependencies": "종속성",
            "Changelog": "변경 로그",
            "changelog": "변경 로그",
            "Release Notes": "릴리스 노트",
            "release notes": "릴리스 노트",
            "Version History": "버전 기록",
            "version history": "버전 기록",
            "Roadmap": "로드맵",
            "roadmap": "로드맵",
            "Plans": "계획",
            "plans": "계획",
            "Future": "향후",
            "future": "향후",
            "Upcoming": "예정",
            "upcoming": "예정",
            "Planned": "계획됨",
            "planned": "계획됨",
            "Proposed": "제안됨",
            "proposed": "제안됨",
            "Draft": "초안",
            "draft": "초안",
            "Work in Progress": "진행 중",
            "work in progress": "진행 중",
            "Under Construction": "공사 중",
            "under construction": "공사 중",
            "Coming Soon": "곧 출시",
            "coming soon": "곧 출시",
            "To Be Determined": "미정",
            "to be determined": "미정",
            "To Be Announced": "추후 공지",
            "to be announced": "추후 공지",
            "Not Yet Implemented": "아직 구현되지 않음",
            "not yet implemented": "아직 구현되지 않음",
            "Not Supported": "지원되지 않음",
            "not supported": "지원되지 않음",
            "Not Implemented": "구현되지 않음",
            "not implemented": "구현되지 않음",
            "Not Available": "사용할 수 없음",
            "not available": "사용할 수 없음",
            "Not Applicable": "해당 없음",
            "not applicable": "해당 없음",
            "Not Specified": "지정되지 않음",
            "not specified": "지정되지 않음",
            "Not Defined": "정의되지 않음",
            "not defined": "정의되지 않음",
            "Not Set": "설정되지 않음",
            "not set": "설정되지 않음",
            "Not Configured": "구성되지 않음",
            "not configured": "구성되지 않음",
            "Not Initialized": "초기화되지 않음",
            "not initialized": "초기화되지 않음",
            "Not Loaded": "로드되지 않음",
            "not loaded": "로드되지 않음",
            "Not Ready": "준비되지 않음",
            "not ready": "준비되지 않음",
        }
    
    def translate(self, text: str) -> str:
        """텍스트를 한국어로 번역합니다."""
        if not text or not isinstance(text, str):
            return text
        
        # 특수문자가 포함된 경우 그대로 반환 (빌드 번호, 해시 등)
        if len(text) > 40 and any(c in text for c in ['/', '\\', '0x', 'http']):
            return text
        
        # 전체 일치 먼저 시도
        if text in self.translations:
            return self.translations[text]
        
        # 대소문자 구분 없이 시도
        text_lower = text.lower()
        if text_lower in self.translations:
            return self.translations[text_lower]
        
        # 부분 번역 시도
        result = text
        for eng, kor in sorted(self.translations.items(), key=lambda x: -len(x[0])):
            if eng in result:
                result = result.replace(eng, kor)
        
        return result


def main():
    """메인 함수"""
    import sys
    
    # 경로 설정
    base_dir = Path(__file__).parent
    input_file = base_dir / "missing_translations" / "missing_keys.json"
    output_file = base_dir / "missing_translations" / "missing_keys_translated_ko.json"
    
    if not input_file.exists():
        print(f"오류: {input_file}을(를) 찾을 수 없습니다!")
        return 1
    
    print(f"입력 파일 읽는 중: {input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # 번역기 초기화
    translator = KoreanTranslator()
    
    print("번역 중...")
    total_keys = 0
    translated_keys = 0
    
    # new_files 배열의 각 파일 처리
    if "new_files" in data:
        for file_entry in data["new_files"]:
            filename = file_entry.get("filename", "")
            keys = file_entry.get("keys", {})
            
            print(f"  처리 중: {filename} ({len(keys)} keys)...")
            
            for key, value in keys.items():
                total_keys += 1
                translated_value = translator.translate(value)
                if translated_value != value:
                    translated_keys += 1
                keys[key] = translated_value
    
    print(f"\n번역 완료:")
    print(f"  총 키 수: {total_keys:,}")
    print(f"  번역된 키 수: {translated_keys:,}")
    print(f"  변경되지 않은 키 수: {(total_keys - translated_keys):,}")
    print(f"  번역률: {(translated_keys / total_keys * 100):.1f}%")
    
    print(f"\n결과 파일 저장 중: {output_file}")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print("완료!")
    return 0


if __name__ == "__main__":
    exit(main())
