import json
with open('missing_translations/missing_keys_korean.json', 'r', encoding='utf-8') as f:
    ko_data = json.load(f)

translations = {
  "action.description.new.line.0": "새 줄 ({0})",
  "action.text.mark.as.nonnls": "NonNls로 표시",
  "action.text.unmark.as.nonnls": "NonNls 표시 해제",
  "comment.if.the.resource.bundle.is.invalid.either.declare.it.as.an.object": "리소스 번들이 유효하지 않으면 소스 코드에서 java.util.ResourceBundle 클래스의 개체로 선언하거나 사용자 지정 리소스 번들 클래스의 메서드를 가리키도록 국제화 템플릿을 편집하세요.",
  "dissociate.resource.bundle.quick.fix.name": "리소스 번들 연결 해제",
  "dissociate.resource.bundle.quick.fix.options.label": "추가 언어 코드:",
  "error.hint.property.has.no.usages": "속성에 사용법(usages)이 없습니다",
  "error.hint.property.has.non.method.usages": "속성에 메서드가 아닌(non-method) 사용법이 있습니다",
  "i18n.quickfix.code.panel.resource.bundle.expression.label": "리소스 번들 표현식(&E):",
  "i18n.quickfix.code.panel.title": "Java 코드 정보",
  "i18n.quickfix.preview.panel.title": "미리 보기",
  "i18nize.dialog.error.jdk.message": "'java.util.ResourceBundle' 클래스를 찾을 수 없습니다.\n올바른 JDK를 설정하세요.",
  "i18nize.dialog.error.jdk.title": "클래스를 찾을 수 없음",
  "i18nize.dialog.template.link.label": "I18n 템플릿 편집",
  "i18nize.error.message": "Java 문자열 리터럴 또는 그 하위 문자열만 I18n(국제화)할 수 있습니다.\nJava 문자열 리터럴 안에 캐럿을 두거나, 그 일부를 선택하세요.",
  "i18nize.error.title": "선택 영역을 I18n(국제화)할 수 없음",
  "i18nize.jsp.error": "I18n(국제화)할 JSP 텍스트를 선택하세요.\n스크립틀릿, 사용자 지정 태그 또는 다른 외국어 요소가 선택되지 않았는지 확인하세요.\n또한, 선택 항목 내부의 HTML 태그는 균형이 맞아야 합니다.",
  "inconsistent.bundle.property.error": "일관되지 않은 속성 ''{0}''입니다. 부모 파일 ''{1}''에 정의되어야 합니다.",
  "inconsistent.bundle.property.inconsistent.end": "일관되지 않은 속성 값 끝(end) ''{0}''",
  "inconsistent.bundle.property.inconsistent.end.parent.end.from.check.symbols": "일관되지 않은 속성 값 끝(end) ''{0}''이지만 ''{2}''에서 ''{1}''이(가) 발견되었습니다",
  "inconsistent.bundle.property.inconsistent.placeholders": "일관되지 않은 자리 표시자 개수: ''{1}''에서 {0}개 발견됨",
  "inconsistent.bundle.property.inherited.with.the.same.value": "동일한 값으로 ''{0}'' 파일에서 상속된 속성입니다",
  "inconsistent.bundle.report.duplicate.properties.values": "동일한 값으로 오버라이딩된 속성 보고(&O)",
  "inconsistent.bundle.report.inconsistent.properties": "일관되지 않은 속성 보고(&I)",
  "inconsistent.bundle.report.inconsistent.properties.ends": "끝(end)이 일관되지 않은 속성 보고(&E)",
  "inconsistent.bundle.report.inconsistent.properties.placeholders": "자리 표시자가 일관되지 않은 속성 보고(&P)",
  "inconsistent.bundle.report.missing.translations": "누락된 번역 보고(&M)",
  "inconsistent.bundle.untranslated.property.error": "번역되지 않은 속성 ''{0}''입니다. ''{1}''에서 오버라이딩되어야 합니다.",
  "inconsistent.resource.bundle.display.name": "일관되지 않은 리소스 번들",
  "inline.property.confirmation": "값 ''{1}''을(를) 가진 ''{0}'' 속성을 인라인화하시겠습니까?",
  "inline.property.refactoring": "인라인 속성",
  "inspection.duplicates.display.name": "중복 문자열 리터럴",
  "inspection.duplicates.message": "<html><body>다음에서 중복된 문자열 리터럴이 발견되었습니다.<br>{0}</body></html>",
  "inspection.duplicates.message.in.this.file": "(이 파일 내)",
  "inspection.duplicates.message.more": "… (그 외 {0}개)",
  "inspection.duplicates.navigate.to.occurrences": "발생 위치로 이동",
  "inspection.duplicates.occurrences.view.title": "''{0}''에 대한 중복",
  "inspection.duplicates.option": "최소 문자열 길이(&M):",
  "inspection.duplicates.option.report.propertykey.expressions": "@PropertyKey 표현식 무시(&I)",
  "inspection.duplicates.replace.family.quickfix": "바꾸기",
  "inspection.duplicates.replace.quickfix": "''{0}''(으)로 바꾸기",
  "inspection.error.dialog.title": "오류",
  "inspection.i18n.display.name": "하드코딩된 문자열",
  "inspection.i18n.expression.is.invalid.error.message": "I18n(국제화) 표현식 템플릿이 유효한 표현식이 아닙니다",
  "inspection.i18n.message.general.with.value": "하드코딩된 문자열 리터럴: {0}",
  "inspection.i18n.message.non.localized.passed.to.localized": "현지화된 문자열이 필요한 곳에 현지화되지 않은 문자열의 참조가 사용되었습니다",
  "inspection.i18n.option.tab.context": "컨텍스트",
  "inspection.i18n.option.tab.literals": "문자열 콘텐츠",
  "inspection.i18n.option.tab.general": "일반",
  "inspection.i18n.option.ignore.nls": "대상이 @Nls로 어노테이트되지 않은 경우 무시",
  "inspection.i18n.option.ignore.nls.description": "이 모드는 어노테이트되지 않은 컨텍스트의 문자열은 현지화할 필요가 없다고 가정합니다.",
  "inspection.i18n.option.report.unannotated.refs": "어노테이트되지 않은 참조 보고",
  "inspection.i18n.option.report.unannotated.refs.description": "예를 들어 어노테이트되지 않은 변수가 @Nls로 어노테이트된 매개변수로 전달될 때 경고를 생성합니다. 이 모드는 @Nls 어노테이션을 전파하는 데 도움이 됩니다.",
  "inspection.i18n.option.suppression.comment": "무시 주석(정규 표현식):",
  "inspection.i18n.option.suppression.comment.description": "코드 줄에 이 정규 표현식과 일치하는 주석이 포함된 경우 해당 리터럴은 보고되지 않습니다.",
  "inspection.i18n.option.ignore.context": "다음 컨텍스트에서는 리터럴을 보고하지 않음:",
  "inspection.i18n.option.ignore.context.assert": "Assert 문 인수",
  "inspection.i18n.option.ignore.context.junit.assert": "JUnit Assert 문 인수",
  "inspection.i18n.option.ignore.context.tostring": "toString() 메서드 안",
  "inspection.i18n.option.ignore.context.assigned.to.constants": "상수에 대입된 리터럴",
  "inspection.i18n.option.ignore.context.enum": "Enum 상수 인수",
  "inspection.i18n.option.ignore.context.exception.constructor": "다음 예외 클래의 생성자 인수:",
  "inspection.i18n.option.no.report.content": "다음 조건에 해당하는 내용의 리터럴은 보고하지 않음…",
  "inspection.i18n.option.no.report.content.qualified.class.names": "...기존의 정규화된 클래스 이름(qualified class name)과 같은 경우",
  "inspection.i18n.option.no.report.content.property.keys": "...기존 속성 키와 같은 경우",
  "inspection.i18n.option.no.report.content.nonalphanumerics": "...알파벳 문자가 포함되지 않은 경우",
  "inspection.i18n.option.no.report.content.string.pattern": "...다음 정규 표현식과 일치하는 경우:",
  "tooltip.example": "예시:",
  "inspection.i18n.quickfix": "하드코딩된 문자열 리터럴 I18n(국제화)",
  "inspection.invalid.resource.bundle.reference": "잘못된 리소스 번들 참조 ''{0}''",
  "inspection.title.capitalization.mix.description": "문자열이 제목과 문장 대소문자 표기 컨텍스트에서 모두 사용되었습니다",
  "inspection.title.capitalization.mismatch.description": "{1} 대소문자 표기가 필요한 곳에 {0} 대소문자 표기가 제공되었습니다",
  "inspection.title.capitalization.description": "문자열 ''{0}''의 대소문자 표기가 적절하지 않습니다. {1} 대소문자 표기를 가져야 합니다",
  "inspection.unresolved.property.key.reference.message": "''{0}''은(는) 유효한 속성 키가 아닌 것 같습니다",
  "inspection.unresolved.property.key.reference.name": "잘못된 속성 키",
  "intention.family.annotate.capitalization.type": "대소문자 표기 유형에 어노테이트 작성",
  "intention.text.edit.property.value": "속성 값 편집",
  "intention.text.suppress.with.0.comment": "''{0}'' 주석으로 무시",
  "introduce.constant.across.the.project": "프로젝트 전체에 상수 도입",
  "progress.title.searching.for.duplicates.of.0": "''{0}''의 중복을 검색하는 중",
  "property.file": "속성 파일:",
  "property.has.more.parameters.than.passed": "속성 ''{0}''은(는) 매개변수 {1}개를 예상했지만, {2}개가 전달되었습니다",
  "quickfix.family.title.capitalization.fix": "적절하게 대소문자 변경",
  "quickfix.i18n.concatentation": "연결된 문자열 I18n(국제화)",
  "quickfix.i18n.concatentation.error": "문자열 연결을 찾을 수 없음",
  "quickfix.text.title.capitalization": "''{0}''의 대소문자 적절하게 변경",
  "rename.prefix.based.property.key.error.message": "이름이 ''{2}''인 접두사 ''{0}''에 기반하여 속성 키 ''{1}''의 이름을 바꿀 수 없습니다. 먼저 접두사를 변경하세요.",
  "resource.bundle.contains.locales.with.suspicious.locale.languages.desciptor": "리소스 번들에 의심되는 로캘 언어가 있는 로캘이 포함되어 있습니다",
  "unused.message.format.parameter.display.name": "메시지 형식 매개변수가 누락됨",
  "unused.message.format.parameter.problem.descriptor": "<code>#ref<code> #loc에서 매개변수 {1}은(는) 사용하지 않고 매개변수 {0}을(를) 사용 중입니다",
  "unsupported.character.display.name": "지원되지 않는 문자",
  "unsupported.character.problem.descriptor": "문자 집합 ''{0}''에 지원되지 않는 문자",
  "unsupported.character.inspection.fix.description": "이스케이프 시퀀스로 변환",
  "intention.family.name.mark.as.nlssafe": "@NlsSafe로 표시",
  "capitalization.kind.title": "제목(title)",
  "capitalization.kind.sentence": "문장(sentence)",
  "value.column.name": "값",
  "key.column.name": "키",
  "command.name.edit.property.value": "속성 값 편집",
  "inspection.dialog.title.capitalization.display.name": "문자열 대소문자 표기법이 잘못됨",
  "inspection.suspicious.locales.languages.display.name": "의심스런 리소스 번들 로캘 언어",
  "inspection.non.basic.latin.character.display.name": "비-기본(Non-Basic) 라틴 문자",
  "inspection.non.basic.latin.character.quickfix": "기본(Basic) 라틴 문자로 변환",
  "i18n.quickfix.preview.description": "다음 문자열을 *.properties 파일에 추출합니다:",
  "inspection.duplicates.navigate.to.occurrences.preview": "프로젝트 내 {1}의 {0}개 발생 위치를 나열합니다.",
  "inspection.duplicates.navigate.to.many.occurrences.preview": "프로젝트 내 {1}의 {0}개 이상의 발생 위치를 나열합니다."
}

ko_error_bundle = next((x for x in ko_data['new_files'] if x['filename'] == 'JavaI18nBundle.properties'), None)
if not ko_error_bundle:
    ko_error_bundle = {'filename': 'JavaI18nBundle.properties', 'keys': {}, 'key_count': 0}
    ko_data['new_files'].append(ko_error_bundle)
ko_error_bundle['keys'].update(translations)
ko_error_bundle['key_count'] = len(ko_error_bundle['keys'])

with open('missing_translations/missing_keys_korean.json', 'w', encoding='utf-8') as f:
    json.dump(ko_data, f, ensure_ascii=False, indent=2)

print("Updated JavaI18nBundle.properties")
