build.target=@@//tools/base/threading-agent:agent_binary
main.class=com.android.tools.instrumentation.threading.agent.Agent
build.time=Thu Jan 01 00\:00\:00 1970 (0)
build.timestamp=Thu Jan 01 00\:00\:00 1970 (0)
build.timestamp.as.int=0
