# The source of truth for these values are in tools/buildSrc/base
# Consistency is maintained via tests

baseVersion = 32.1.0
buildVersion = 9.1.0
cmdlineToolsVersion = 21.0-alpha01
apiVersion = 3
nativeApiVersion = 0

lastStableBuildVersion = 9.0.1

isAgpReleaseBranch = true
