build.target=@@//tools/base/tracer:agent_binary
main.class=com.android.tools.tracer.agent.TraceAgent
build.time=Thu Jan 01 00\:00\:00 1970 (0)
build.timestamp=Thu Jan 01 00\:00\:00 1970 (0)
build.timestamp.as.int=0
