# default properties for swingx
# JXSearchPanel

Search.matchCase=대소문자 구분
Search.contains=포함
Search.equals=일치
Search.endsWith=끝말
Search.startsWith=시작말

Search.wrapSearch=검색 줄바꿈
Search.backwardsSearch=되돌리기
Search.match=찾기
Search.close=닫기
Search.findNext=다음 찾기
Search.findPrevious=이전 찾기
Search.searchFieldLabel=찾기
Search.searchFieldLabel.mnemonic=F
Search.searchTitle=찾기

Search.notFound=값을 찾을 수 없음
Search.notFoundBackground=FF6666
Search.notFoundForeground=000000

XDialog.close=닫기
XDialog.cancel=취소
XDialog.execute=확인

# default properties for swingx
# JXTable column control entries
#
JXTable.column.horizontalScroll=가로 스크롤
JXTable.column.packAll=모든 열 압축
JXTable.column.packSelected=선택한 열 압축

#
# default actions in context menues for TextComponents
#
DefaultEditorKit.cut-to-clipboard=잘라내기
DefaultEditorKit.copy-to-clipboard=복사
DefaultEditorKit.paste-from-clipboard=붙여넣기
DefaultEditorKit.delete-next=삭제
DefaultEditorKit.select-all=모두 선택

#
# default actions for context menus for ScrollBars
#
JScrollBar.vertical.minScroll=맨 위로
JScrollBar.vertical.maxScroll=맨 아래로
JScrollBar.vertical.negativeUnitIncrement=위로 스크롤
JScrollBar.vertical.negativeBlockIncrement=위로 페이지
JScrollBar.vertical.positiveUnitIncrement=아래로 스크롤
JScrollBar.vertical.positiveBlockIncrement=아래로 페이지

JScrollBar.horizontal.minScroll=왼쪽 가장자리
JScrollBar.horizontal.maxScroll=오른쪽 가장자리
JScrollBar.horizontal.negativeUnitIncrement=왼쪽으로 스크롤
JScrollBar.horizontal.negativeBlockIncrement=왼쪽으로 페이지
JScrollBar.horizontal.positiveUnitIncrement=오른쪽으로 스크롤
JScrollBar.horizontal.positiveBlockIncrement=오른쪽으로 페이지
