package org.jetbrains.plugins.koreanlanguagepack

// generate_action_override_kotlin.py 로 자동 생성됨. 직접 수정하지 말 것.
//
// Android/Compose/NDK 등 다른 플러그인이 plugin.xml에 text=/description= 을
// 인라인으로 박아넣은 액션·그룹들의 한국어 번역. 이런 액션은 리소스 번들 키
// (action.<id>.text)를 통한 오버라이드가 적용되지 않기 때문에
// InlineActionTextOverrideApplier 가 ActionManager로 직접 텍스트를 덮어쓴다.
internal val INLINE_ACTION_TEXT_OVERRIDES: Map<String, String> = mapOf(
    "AcceptSuggestionAction" to "선택한 제안 수락",
    "ActivateDebugToolWindow" to "디버그",
    "AddBreakpoint" to "중단점 추가",
    "AddConditionalBreakpoint" to "조건부 중단점 추가…",
    "AddLoggingBreakpoint" to "로깅 중단점 추가…",
    "Adtui.ZoomInAction" to "확대",
    "Adtui.ZoomOutAction" to "축소",
    "Adtui.ZoomResetAction" to "확대/축소 재설정",
    "Adtui.ZoomToActualAction" to "실제 크기로 보기(100%)",
    "Adtui.ZoomToFitAction" to "화면에 맞추기",
    "AgpUpgrade" to "AGP 업그레이드 어시스턴트...",
    "Android Profiler" to "프로파일",
    "Android.AdbDevicePairing" to "Wi-Fi로 기기 페어링",
    "Android.AddCppToModule" to "모듈에 C++ 추가",
    "Android.AnalyzeApk" to "APK 분석...",
    "Android.BuildApk" to "APK 생성",
    "Android.BuildApkOrBundle" to "앱 번들 또는 APK 생성",
    "Android.BuildBundle" to "번들 생성",
    "Android.ChooseProfileConfiguration" to "프로파일링...",
    "Android.Compose.MeshGradientEditorAction" to "메시 그라디언트 편집기...",
    "Android.ConvertToNinePatch" to "9-Patch 파일 생성…",
    "Android.CreateResourceDirectory" to "Android 리소스 디렉터리",
    "Android.CreateResourcesActionGroup" to "Android 리소스 파일",
    "Android.CreateSampleDataDirectory" to "샘플 데이터 디렉터리",
    "Android.Designer.AddAction" to "작업 추가",
    "Android.Designer.AddDeepLink" to "딥 링크 추가",
    "Android.Designer.AssignStartDestination" to "시작 대상 지정",
    "Android.Designer.AutoArrange" to "자동 정렬",
    "Android.Designer.CommonActions.ForceCompileAndRefreshActionForNotification" to "빌드 및 새로고침",
    "Android.Designer.ComposeIssueNotificationAction" to "문제 패널 전환",
    "Android.Designer.ForceRefreshPreview" to "레이아웃 강제 새로고침",
    "Android.Designer.GenerateComposePreviewAgentAction" to "Compose 미리보기",
    "Android.Designer.GenerateSingleComposePreviewForFileAction" to "Composable에 대한 미리보기 생성",
    "Android.Designer.IssueNotificationAction" to "문제 패널 전환",
    "Android.Designer.IssuePanel.CopyIssueDescription" to "문제 설명 복사",
    "Android.Designer.IssuePanel.QuickFixes" to "빠른 수정 표시",
    "Android.Designer.IssuePanel.SeverityFilter" to "보기 옵션",
    "Android.Designer.IssuePanel.ToggleIssueDetailAction" to "문제 세부정보 표시",
    "Android.Designer.LayoutEditorActions" to "레이아웃 편집기",
    "Android.Designer.NavEditorActions" to "탐색 편집기",
    "Android.Designer.NextDevice" to "다음 기기 미리보기",
    "Android.Designer.PreviousDevice" to "이전 기기 미리보기",
    "Android.Designer.ScreenshotToCodeAction" to "이미지로 코드 생성",
    "Android.Designer.ScreenshotToCodeAction.New" to "이미지로 코드 생성",
    "Android.Designer.SwitchDesignMode" to "디자인 모드 전환",
    "Android.Designer.SwitchLayoutQualifier" to "레이아웃 한정자 전환",
    "Android.Designer.ToggleDeviceNightMode" to "기기 야간 모드 전환",
    "Android.Designer.ToggleDeviceOrientation" to "기기 방향 전환",
    "Android.Device.Picker.Help" to "도움말",
    "Android.DisableAllPlugins" to "모든 플러그인 비활성화",
    "Android.ExportProjectZip" to "ZIP 파일로 내보내기...",
    "Android.GenerateSignedApk" to "서명된 앱 번들 또는 APK 생성…",
    "Android.OpenStringResourceEditor" to "번역 편집기 열기",
    "Android.Profile" to "프로파일",
    "Android.ProfileWithCompleteData" to "프로파일",
    "Android.ProfileWithLowOverhead" to "프로파일",
    "Android.PublishActionGroup" to "게시",
    "Android.RunAndroidSdkManager" to "SDK 관리자",
    "Android.RunLayoutInspector" to "레이아웃 검사기",
    "Android.ShowLicenses" to "라이선스",
    "Android.SyncProject" to "Gradle 파일과 프로젝트 동기화",
    "Android.ValidateEssentialPlugins" to "필수 플러그인 검증",
    "AndroidAddRTLSupport" to "가능한 곳에 RTL 지원 추가...",
    "AndroidConnectDebuggerAction" to "Android 프로세스에 디버거 연결",
    "AndroidExtractAsIncludeAction" to "레이아웃...(&L)",
    "AndroidExtractStyleAction" to "스타일...(&Y)",
    "AndroidFindStyleApplicationsAction" to "가능한 곳에 스타일 사용...(&W)",
    "AndroidInlineIncludeAction" to "레이아웃 인라인화...(&L)",
    "AndroidInlineStyleReferenceAction" to "스타일 인라인화...(&S)",
    "AndroidMigrateBuildConfigFromGradlePropertiesToDsl" to "BuildConfig를 Gradle 빌드 파일로 마이그레이션",
    "AndroidMigrateResValuesFromGradlePropertiesToDsl" to "ResValues를 Gradle 빌드 파일로 마이그레이션",
    "AndroidMigrateToDefaultTargetSdkToCompileSdkValueIfUnset" to "TargetSdk를 CompileSdk로 기본 설정",
    "AndroidMigrateToNonTransitiveRClassesAction" to "비전이적 R 클래스로 마이그레이션...",
    "AndroidMigrateToResourceNamespacesAction" to "리소스 네임스페이스로 마이그레이션...",
    "AndroidModularizeAction" to "모듈화...",
    "AndroidToolsGroup" to "Android",
    "AndroidUnusedDependenciesAction" to "AI로 모든 라이브러리 업데이트",
    "AndroidUnusedResourceAction" to "사용하지 않는 리소스 제거...",
    "AndroidX.BaselineProfile.RunGenerate" to "전체 앱 베이스라인 프로필 생성",
    "AssembleGradleModule" to "모듈 빌드",
    "AssembleGradleProjectWithTests" to "테스트 포함 프로젝트 빌드",
    "AssembleRunConfiguration" to "선택한 실행 구성 빌드",
    "AvailableDevices" to "사용 가능한 기기",
    "BuildViewFilterSuccessful" to "성공한 단계 표시",
    "BuildViewFilterWarnings" to "경고 표시",
    "CIDR.Debugger.CidrMemoryToggleDebugInlaysAction" to "메모리 문서에 디버그 인레이 표시",
    "CIDR.Debugger.CidrToggleGdbMiFrameVariablesAction" to "GDB: GDB/MI 변수 보기 표시",
    "CIDR.Debugger.DisablePadding" to "패딩 없음",
    "CIDR.Debugger.PadToByte" to "바이트 단위로 패딩",
    "CIDR.Debugger.PadToSize" to "크기에 맞게 패딩",
    "CIDR.Debugger.ViewAsBinary" to "2진수",
    "CIDR.Debugger.ViewAsDecimal" to "10진수",
    "CIDR.Debugger.ViewAsDefault" to "기본값",
    "CIDR.Debugger.ViewAsGroup.Popup" to "다음으로 보기…",
    "CIDR.Debugger.ViewAsHex" to "16진수",
    "CIDR.Debugger.ViewAsOctal" to "8진수",
    "CPP.ProjectView.ShowFilesUnknownToCMake" to "CMake에 알려지지 않은 파일 표시",
    "ChangeGradleJdkLocation" to "Gradle JDK 위치 변경",
    "ChangeReview.RunChangeReviewForCommitAction" to "AI로 커밋 리뷰하기",
    "ChangeReview.RunChangeReviewForPendingChangesAction" to "AI로 대기 중인 변경사항 리뷰하기",
    "ChangesView.SelectFile" to "변경사항 보기에서 열린 파일 선택",
    "CleanGradleProject" to "프로젝트 정리(Clean)",
    "CodeReview.NextComment" to "다음 댓글",
    "CodeReview.PreviousComment" to "이전 댓글",
    "CollectMemoryUsageStatistics" to "Studio 구성 요소 메모리 사용량 통계 수집",
    "CollectZippedLogs" to "로그 및 진단 데이터 수집",
    "CompileAllSources" to "모든 소스 컴파일",
    "CompileGradleModule" to "모듈 컴파일",
    "Compose.Live.Edit.ManualLiveEdit" to "수동 라이브 에딧",
    "Compose.Live.Edit.Refresh" to "새로고침",
    "Compose.Live.Edit.ShowLogcat" to "Logcat 표시",
    "Console.TableResult.EditMaximized.ArrayGrid.ToggleHideDeleted" to "삭제된 요소 숨기기",
    "ConvertJavaToKotlinGroup" to "Java를 Kotlin으로 변환",
    "ConvertJavaToKotlinInGroup" to "정적 분석",
    "ConvertToWindowsLineSeparators" to "CRLF - Windows (\\r\\n)",
    "CopyTBXReference" to "Toolbox URL",
    "CreateAllServicesAndExtensions" to "모든 서비스 및 확장 생성",
    "CreateLibraryFromFile" to "라이브러리로 추가...",
    "DeadlockUIThread" to "Lock으로 UI 스레드 교착 상태 생성",
    "DeadlockUIThreadWithReadAction" to "읽기 작업으로 UI 스레드 교착 상태 생성",
    "DeadlockUIThreadWithSynchronized" to "Synchronized로 UI 스레드 교착 상태 생성",
    "DeadlockUIThreadWithTimeout" to "Lock으로 UI 스레드 교착 상태 생성(10초 제한 시간)",
    "DebugToolbarQuickActions" to "디버거 도구모음에 추가",
    "Debugger.AddInlineWatch" to "인라인 Watch 추가",
    "Debugger.AddToWatch" to "Watch에 추가",
    "Debugger.CopyStack" to "스택 복사",
    "Debugger.EvaluateInConsole" to "콘솔에서 계산",
    "Debugger.FocusOnBreakpoint" to "중단점에서 포커스 이동",
    "Debugger.FocusOnFinish" to "종료 시 포커스 이동",
    "Debugger.FreezeActiveThreadAction" to "스레드 서스펜드",
    "Debugger.FreezeInactiveThreadsAction" to "다른 스레드 서스펜드",
    "Debugger.FreezeInactiveThreadsAmongSelected" to "그룹 내 비활성 스레드 서스펜드",
    "Debugger.FreezeSelectedThreads" to "스레드 서스펜드",
    "Debugger.MarkObject" to "객체 표시…",
    "Debugger.RemoveAllBreakpoints" to "모든 중단점 제거",
    "Debugger.RemoveAllBreakpointsInFile" to "현재 파일의 모든 중단점 제거",
    "Debugger.ShowReferring" to "참조 객체 표시…",
    "Debugger.ThawActiveThreadAction" to "스레드 재개",
    "Debugger.ThawAllThreadsAction" to "모든 스레드 재개",
    "Debugger.ThawSelectedThreads" to "스레드 재개",
    "Debugger.Tree.EvaluateInConsole" to "콘솔에서 계산",
    "DeveloperServices.ConnectionAssistant" to "기기 연결 문제 해결",
    "DeveloperServices.Firebase" to "Firebase",
    "DeveloperServices.TargetSDKVersionUpgradeAssistant" to "Android SDK 업그레이드 어시스턴트",
    "DeveloperServices.UrlAssistant" to "App Links 어시스턴트",
    "DeviceAndSnapshotComboBox" to "기기 선택",
    "DropAnError" to "오류 발생시키기",
    "DropAnErrorWithAttachments" to "첨부 파일이 있는 오류 발생시키기",
    "DropAnOutOfMemoryError" to "OutOfMemoryError 발생시키기",
    "DropPluginError" to "임의의 플러그인에서 오류 발생시키기",
    "DumpJFR" to "JFR 기록 덤프",
    "DumpUastLog" to "UAST 트리 덤프",
    "DumpUastLogByElement" to "PsiElement별 UAST 트리 덤프",
    "EditorSelectWordAtCurrentCaret" to "선택 영역 확장",
    "FreezeUI" to "UI 정지",
    "GenerateSourcesModuleAction" to "소스 생성 Gradle 작업 실행",
    "Git.Checkout.Update" to "체크아웃 및 업데이트",
    "Git.CherryPick.Continue" to "체리픽 계속하기",
    "Git.ContextMenu" to "Git",
    "Git.CreateNewWorkingTree" to "새 Worktree…",
    "Git.Log.HighlightCherryPickedCommits" to "체리픽되지 않은 커밋",
    "Git.Menu" to "Git",
    "Git.Show.WorkingTrees" to "Worktree…",
    "Git.Stage.Index.File.Menu" to "Git",
    "Git.WorkingTrees.Open" to "열기",
    "Git.WorkingTrees.Refresh" to "새로고침",
    "Git.WorkingTrees.Remove" to "삭제…",
    "GitHub.MainMenu" to "GitHub",
    "GitHub.Timeline.DeleteMergedBranch" to "브랜치 삭제",
    "GitLab.Main.Group" to "GitLab",
    "GitOpenExistingWorkingTreeForLocalBranchAction" to "Worktree 열기…",
    "Github.Break.Api.Requests" to "GitHub API 요청 중단",
    "GoToRelatedDaggerItemsAction" to "관련 Dagger 항목으로 이동",
    "GoogleCloudTesting.RoboScriptRecorder" to "Robo 스크립트 녹화",
    "GoogleCloudTesting.TestRecorder" to "Espresso 테스트 녹화",
    "GoogleCloudTools.SampleImport" to "샘플 가져오기...",
    "GoogleLoginV2.LoginService" to "Google 로그인 V2",
    "HelpTopics" to "Android Studio 도움말",
    "IdeaNewModule" to "IDEA 새 모듈...",
    "IdeaNewProject" to "IDEA 새 프로젝트...",
    "IgnoreGradleChanges" to "Gradle 변경사항 무시",
    "ImportApkAction" to "APK 프로파일링 또는 디버그...",
    "ImportModule" to "모듈 가져오기...",
    "ImportProject" to "프로젝트 가져오기...",
    "ImportWatchFaceStudioFileAction" to "Watch Face Studio 파일 가져오기...",
    "InferAnnotations" to "어노테이션 추론...",
    "InferNullity" to "Nullity 추론...",
    "InspectPlayPolicyCode" to "Play 정책 인사이트 검사...",
    "IntelliJ.HelpTopics" to "IntelliJ IDEA 도움말",
    "Internal.Android.FreezeTools" to "정지(Freeze)",
    "Internal.JavaFlightRecorder" to "Java Flight Recorder",
    "Jcef.ContextMenuGroup" to "JCEF 프런트엔드 작업",
    "LayoutEditor.HelpAssistant" to "도움말 패널 표시",
    "LayoutEditor.HelpAssistant.ConstraintLayout" to "Constraint Layout 도움말 패널",
    "LayoutEditor.HelpAssistant.Full" to "도움말 패널 표시",
    "LayoutEditor.HelpAssistant.MotionLayout" to "Motion Layout 도움말 패널",
    "LegacyNewAndroidComponent" to "Android 구성 요소",
    "LibraryProperties" to "라이브러리 속성...",
    "Logcat.ClearLogcat" to "Logcat 패널 지우기",
    "Logcat.LogcatActions" to "Logcat",
    "Logcat.PauseResumeLogcat" to "Logcat 일시정지/재개",
    "Logcat.RestartLogcat" to "Logcat 재시작",
    "Logcat.ToggleSoftWrap" to "자동 줄바꿈",
    "Logcat.ToggleViewFormat" to "Logcat 형식 전환",
    "MakeGradleProject" to "프로젝트 빌드(Assemble)",
    "Markdown.Tools" to "Markdown",
    "MemoryView.ShowOnlyWithDiff" to "차이가 있는 항목만 표시",
    "MemoryView.SwitchUpdateMode" to "디버거 정지 시 로드된 클래스 업데이트",
    "NavEditor.HelpAssistant" to "도움말 패널 표시",
    "NewAndroidImageAsset" to "이미지 애셋",
    "NewAndroidVectorAsset" to "벡터 애셋",
    "NewModule" to "새 모듈…",
    "NewModuleInGroup" to "모듈",
    "NewVersionCatalogFile" to "버전 카탈로그",
    "NewXml" to "XML",
    "NextEditPredictionCancelAction" to "다음 편집 예측 취소",
    "NextEditPredictionProceedAction" to "다음 편집 예측 이동 또는 수락",
    "OpenFile" to "열기…",
    "PrintModulesAndEntitySources" to "모듈 및 엔티티 소스를 로그에 출력",
    "Project.CallGraph" to "문맥별 호출 경로",
    "Project.InterproceduralThreadAnnotations" to "프로시저 간 스레드 어노테이션 검사기",
    "ReactivePostOpenProjectActionsAction" to "Kotlin 프로젝트 열기 후 작업",
    "RebuildGradleProject" to "테스트 포함 프로젝트 정리 및 빌드",
    "RefreshLinkedCppProjects" to "연결된 C++ 프로젝트 새로고침",
    "ResetUserIdAction" to "데이터 공유 사용자 식별자 재설정",
    "ResourceExplorer.CopyValue" to "값 복사",
    "ResourceExplorer.open" to "리소스 관리자",
    "ResourceExplorer.show" to "리소스 관리자에 표시",
    "RestoreDefaultLayout" to "기본 레이아웃 복원",
    "RunToolbarPauseAction" to "일시 정지",
    "RunToolbarResumeAction" to "재개",
    "RunningDevices" to "실행 중인 기기",
    "SeNewSearchToggleAction" to "새로운 검색 방식(Split Search) 사용",
    "SelectBuildVariant" to "빌드 변형 선택...",
    "SelectMultipleDevices" to "여러 기기 선택...",
    "SelectProjectAction" to "기기 스트리밍 프로젝트 구성",
    "ShowBuildFilesInModuleAction" to "모듈의 빌드 파일 표시",
    "ShowMarketingDialog" to "마케팅 대화상자 표시",
    "ShowNextEditPredictionMenuAction" to "다음 편집 예측 메뉴 표시",
    "ShowPoweredProgress" to "Powered Progress 표시",
    "ShowWorkspaceFileState" to "워크스페이스 파일 상태 표시",
    "SimulateFreeze" to "정지 상태 시뮬레이션",
    "SplittingTabsToolWindow.MoveTabLeft" to "탭 왼쪽으로 이동",
    "SplittingTabsToolWindow.MoveTabRight" to "탭 오른쪽으로 이동",
    "SplittingTabsToolWindow.RenameTab" to "탭 이름 변경",
    "StatisticsViewer" to "통계 뷰어 표시",
    "StoreDefaultLayout" to "현재 레이아웃을 기본값으로 저장",
    "Table-selectFirstColumn" to "첫 번째 열 선택",
    "Table-selectFirstColumnExtendSelection" to "첫 번째 열까지 선택 확장",
    "Table-selectLastColumn" to "마지막 열 선택",
    "Table-selectLastColumnExtendSelection" to "마지막 열까지 선택 확장",
    "TemplateProjectStructure" to "기본 프로젝트 구조...",
    "Terminal.AiAgents.AgentSelector" to "AI 에이전트",
    "Terminal.AiAgents.ChevronSelector" to "AI 에이전트 선택",
    "Terminal.AiAgents.LaunchSelectedAgent" to "AI 에이전트",
    "Terminal.AiAgents.ToggleShowAiAgentsInToolbar" to "도구모음에 AI 에이전트 표시",
    "TodoMainGroup" to "TODO",
    "TouchBar" to "Touchbar",
    "UastInternal" to "UAST",
    "UserInvokedHeapDumpSnapshot" to "메모리 사용량 분석",
    "VcsGroups" to "Git",
    "WelcomeScreen.AndroidStudio.apkProfilingAndDebugging" to "APK 프로파일링 또는 디버그",
    "WelcomeScreen.Configure.ProjectStructure" to "기본 프로젝트 구조...",
    "WelcomeScreen.CreateNewProject" to "새 프로젝트",
    "WelcomeScreen.GoogleCloudTools.SampleImport" to "Android 코드 샘플 가져오기",
    "WelcomeScreen.OpenProject" to "열기",
    "WelcomeScreen.RunAndroidSdkManager" to "SDK 관리자",
    "WelcomeScreen.RunDeviceManager2" to "가상 기기 관리자",
    "WhatsNewEditorAction" to "Android Studio 새 기능",
    "XDebugger.Attach.Dialog.Settings" to "연결 대화상자 설정",
    "XDebugger.CompareValueWithClipboard" to "클립보드 값과 비교",
    "XDebugger.CopyName" to "이름 복사",
    "XDebugger.CopyValue" to "값 복사",
    "XDebugger.CopyWatch" to "Watch 복제",
    "XDebugger.DisableAllButThisBreakpoint" to "다른 중단점 비활성화",
    "XDebugger.EditWatch" to "편집…",
    "XDebugger.Inline" to "에디터에 변수 값 표시",
    "XDebugger.Inspect" to "검사…",
    "XDebugger.JumpToSource" to "소스로 이동",
    "XDebugger.JumpToTypeSource" to "타입 소스로 이동",
    "XDebugger.MoveWatchDown" to "Watch 아래로 이동",
    "XDebugger.MoveWatchUp" to "Watch 위로 이동",
    "XDebugger.MuteBreakpoints" to "중단점 음소거",
    "XDebugger.NewWatch" to "새 Watch…",
    "XDebugger.PauseWatch" to "Watch 일시 정지",
    "XDebugger.PinToTop" to "맨 위에 고정",
    "XDebugger.PreviewTab" to "미리보기 탭에서 파일 열기",
    "XDebugger.RemoveAllButThisBreakpoint" to "다른 중단점 제거",
    "XDebugger.RemoveAllWatches" to "모든 Watch 제거",
    "XDebugger.RemoveWatch" to "Watch 제거",
    "XDebugger.SeparateWatches" to "Watch 분리",
    "XDebugger.SetValue" to "값 설정…",
    "XDebugger.Show.Breakpoints.Over.Line.Numbers" to "줄 번호 위에 중단점 표시",
    "XDebugger.ToggleEvaluateExpressionField" to "표현식 계산 필드 표시",
    "XDebugger.ToggleSortValues" to "변수 알파벳순 정렬",
    "XDebugger.UnmuteOnStop" to "세션 종료 시 중단점 음소거 해제",
    "action.android.backup" to "앱 데이터 백업",
    "action.android.backup.foreground.app" to "앱 데이터 백업",
    "action.android.restore" to "앱 데이터 복원",
    "action.android.restore.file" to "앱 데이터 복원",
    "action.android.restore.group" to "앱 데이터 복원",
    "aiplugin.agents.planning.editor.internal.planningModeEditorDialog" to "계획 모드 편집기 프로토타입 대화상자",
    "aiplugin.chat.addtocontext" to "현재 파일을 채팅 컨텍스트에 추가",
    "aiplugin.chat.explaintthis" to "이것 설명하기",
    "aiplugin.custom.transform" to "에디터 내 프롬프트 열기",
    "aiplugin.custom.transform.finishchanges" to "변경 완료",
    "aiplugin.gemini.editor.group" to "AI",
    "aiplugin.mcp.client.listTools" to "MCP 도구 목록",
    "android.deploy.ApplyChanges" to "변경사항 적용 및 액티비티 재시작",
    "android.deploy.CodeSwap" to "코드 변경사항 적용",
    "android.deploy.DebugWithoutBuild" to "빌드 없이 디버그",
    "android.deploy.RunWithoutBuild" to "빌드 없이 실행",
    "android.device.back.button" to "뒤로",
    "android.device.home.button" to "홈",
    "android.device.overview.button" to "개요",
    "android.device.postures" to "접기/펼치기",
    "android.device.power.and.volume.up.button" to "전원 + 볼륨 올리기(전원 메뉴)",
    "android.device.power.button" to "전원",
    "android.device.reservation.end" to "기기 반환 및 초기화",
    "android.device.reservation.extend" to "예약 연장",
    "android.device.rotate.left" to "왼쪽으로 회전",
    "android.device.rotate.right" to "오른쪽으로 회전",
    "android.device.screen.record" to "화면 녹화",
    "android.device.screenshot" to "스크린샷 찍기",
    "android.device.sleep" to "손바닥 제스처",
    "android.device.volume.down.button" to "볼륨 내리기",
    "android.device.volume.up.button" to "볼륨 올리기",
    "android.device.wear.whs" to "Wear Health Services",
    "android.device.wear1.button" to "버튼 1",
    "android.device.wear2.button" to "버튼 2",
    "android.emulator.display.mode" to "디스플레이 모드",
    "android.emulator.display.mode.foldable" to "폴더블",
    "android.emulator.display.mode.phone" to "휴대폰",
    "android.emulator.display.mode.tablet" to "태블릿",
    "android.emulator.environment.camera" to "카메라",
    "android.emulator.environment.custom" to "사용자 지정 환경...",
    "android.emulator.environment.darkness" to "완전 어두움",
    "android.emulator.environment.recent" to "최근 사용자 지정 환경",
    "android.emulator.environments" to "환경",
    "android.emulator.extended.controls" to "확장 컨트롤",
    "android.emulator.glasses.camera.button" to "카메라",
    "android.emulator.glasses.display.button" to "디스플레이",
    "android.emulator.glasses1.button" to "카메라",
    "android.emulator.glasses2.button" to "디스플레이",
    "android.emulator.snapshots" to "스냅샷",
    "android.emulator.tilt" to "기울이기",
    "android.emulator.virtual.sensors" to "가상 센서",
    "android.streaming.benchmark" to "스트리밍 기기 벤치마크",
    "android.streaming.hardware.input" to "하드웨어 입력",
    "android.streaming.microphone.input" to "마이크 연결/연결 해제",
    "android.streaming.ui.settings" to "기기 UI 바로가기",
    "android.streaming.xr.eye.tracking" to "시선 추적",
    "android.streaming.xr.hand.tracking" to "손 추적",
    "android.streaming.xr.input.mode.dropdown" to "앱과 상호작용",
    "android.streaming.xr.interaction" to "앱과 상호작용",
    "android.streaming.xr.interaction.eye" to "시선 추적",
    "android.streaming.xr.interaction.hand" to "손 추적",
    "android.streaming.xr.interaction.mouse" to "마우스와 키보드 연결",
    "android.streaming.xr.location.in.space.xy" to "좌우/상하 이동",
    "android.streaming.xr.location.in.space.z" to "앞뒤 이동",
    "android.streaming.xr.passthrough" to "패스스루 전환",
    "android.streaming.xr.passthrough.toggle" to "패스스루 전환",
    "android.streaming.xr.recenter" to "시야 재설정",
    "android.streaming.xr.view.direction" to "시야 방향",
    "android.streaming.zoom.actual" to "실제 크기로 보기(100%)",
    "android.streaming.zoom.fit" to "창에 맞추기",
    "android.streaming.zoom.fit.inner" to "디스플레이를 창에 맞추기",
    "android.streaming.zoom.in" to "확대",
    "android.streaming.zoom.out" to "축소",
    "com.android.build.attribution.ui.OpenBuildAnalyzerAction" to "빌드 성능 분석",
    "com.android.build.attribution.ui.OpenBuildAnalyzerResultsAction" to "이전 빌드 결과 분석 표시",
    "com.android.screenshottest.action.UpdateReferenceImagesAction" to "참조 이미지 추가/업데이트",
    "com.android.screenshottest.action.UpdateReferenceImagesFromTestPanelAction" to "참조 이미지 업데이트...",
    "com.android.screenshottest.action.UpdateReferenceImagesInClassAction" to "참조 이미지 추가/업데이트",
    "com.android.screenshottest.action.UpdateReferenceImagesInDirectoryAction" to "참조 이미지 추가/업데이트",
    "com.android.studio.ml.npa.RunNewProjectAgentAction" to "새 프로젝트 에이전트 실행",
    "com.android.tools.adtui.webp.WebpSupportTestAction" to "WebP 지원 테스트 작업",
    "com.android.tools.idea.actions.HideAndroidBannerAction" to "Android 배너 숨기기",
    "com.android.tools.idea.layoutinspector.toggle.layout.inspector.action" to "레이아웃 검사기 전환",
    "com.google.studiobot.container.trajectory.ActivateChatAction" to "에이전트 창 열기",
    "com.google.studiobot.container.trajectory.CreateNewConversationAction" to "새 에이전트 채팅",
    "com.google.studiobot.container.trajectory.CycleConversationsAction" to "활성 채팅 간 전환",
    "com.google.studiobot.container.trajectory.MoveToNextConversationAction" to "다음 채팅",
    "com.google.studiobot.container.trajectory.MoveToPreviousConversationAction" to "이전 채팅",
    "com.google.studiobot.container.trajectory.NewTrajectoryTabAction" to "새 에이전트 탭",
    "com.google.tools.intellij.aiplugin.action.SelectGcpProjectAction" to "Gemini Code Assist 프로젝트 선택...",
    "com.google.tools.intellij.aiplugin.recitation.IgnorePromptRecitationAction" to "코드 참조 무시",
    "hg4idea.file.menu" to "Mercurial",
    "sml.AnalyzeThreadSafety" to "스레드 안전성 분석",
    "sml.GenerateReadmeAction" to "README 생성",
    "sml.KeepChange" to "유지",
    "sml.MergeConflictsWithAgentAction" to "에이전트로 충돌 병합",
    "sml.ResumeMigrationAction" to "마이그레이션 재개",
    "sml.RevertChange" to "되돌리기",
    "sml.SuggestCommitMessageAction" to "커밋 메시지 제안",
    "sml.studiobot.quick.edit" to "빠른 편집",
    "sml.studiobot.rag.internal.group" to "RAG 내부 작업",
)

internal val INLINE_ACTION_DESCRIPTION_OVERRIDES: Map<String, String> = mapOf(
    "Adtui.ZoomInAction" to "미리보기 확대",
    "Adtui.ZoomOutAction" to "미리보기 축소",
    "Adtui.ZoomResetAction" to "확대/축소 수준을 기본값으로 재설정",
    "Adtui.ZoomToActualAction" to "미리보기를 실제 크기로 표시",
    "Adtui.ZoomToFitAction" to "미리보기를 화면 크기에 맞춤",
    "AgpUpgrade" to "프로젝트의 Android Gradle 플러그인(AGP) 종속성을 업그레이드합니다",
    "Android Profiler" to "선택한 구성을 프로파일링합니다",
    "Android.AdbDevicePairing" to "Wi-Fi를 통해 기기를 연결할 수 있는 기기 페어링 대화상자를 엽니다",
    "Android.AddCppToModule" to "CMake 또는 ndk-build로 빌드된 C/C++ 코드를 이 모듈에 추가합니다",
    "Android.ChooseProfileConfiguration" to "구성을 선택하고 프로파일링합니다",
    "Android.Compose.MeshGradientEditorAction" to "메시 그라디언트 편집기 플레이그라운드를 실행합니다",
    "Android.CreateResourceDirectory" to "새 리소스 파일 생성",
    "Android.CreateSampleDataDirectory" to "새 샘플 데이터 디렉터리 생성",
    "Android.Designer.AddAction" to "선택한 항목에 작업을 추가합니다",
    "Android.Designer.AddDeepLink" to "선택한 항목에 딥 링크를 추가합니다",
    "Android.Designer.AssignStartDestination" to "탐색 그래프의 시작점을 지정합니다",
    "Android.Designer.AutoArrange" to "항목을 다시 정렬합니다",
    "Android.Designer.CommonActions.ForceCompileAndRefreshActionForNotification" to "최신 코드 변경사항으로 미리보기를 업데이트합니다",
    "Android.Designer.ComposeIssueNotificationAction" to "문제 패널의 표시 여부를 전환합니다",
    "Android.Designer.ForceRefreshPreview" to "미리보기를 새로고침합니다",
    "Android.Designer.IssueNotificationAction" to "문제 패널의 표시 여부를 전환합니다",
    "Android.Designer.NextDevice" to "기기 메뉴에서 다음 기기로 변경합니다",
    "Android.Designer.PreviousDevice" to "기기 메뉴에서 이전 기기로 변경합니다",
    "Android.Designer.ScreenshotToCodeAction" to "첨부된 이미지로 Jetpack Compose 코드를 생성합니다",
    "Android.Designer.ScreenshotToCodeAction.New" to "첨부된 이미지로 Jetpack Compose 코드를 생성합니다",
    "Android.Designer.SwitchDesignMode" to "디자인, 블루프린트, 디자인+블루프린트 모드를 순환하며 전환합니다",
    "Android.Designer.SwitchLayoutQualifier" to "현재 레이아웃의 한정자를 전환하거나 새로 만듭니다",
    "Android.Designer.ToggleDeviceNightMode" to "미리보기의 야간 모드를 켜거나 끕니다",
    "Android.Designer.ToggleDeviceOrientation" to "미리보기 방향을 세로와 가로 사이에서 전환합니다",
    "Android.Profile" to "선택한 구성을 프로파일링합니다",
    "Android.ProfileWithCompleteData" to "선택한 구성을 프로파일링합니다",
    "Android.ProfileWithLowOverhead" to "선택한 구성을 프로파일링합니다",
    "Android.RunLayoutInspector" to "선택한 창의 레이아웃을 검사합니다",
    "AndroidAddRTLSupport" to "가능한 곳에 오른쪽에서 왼쪽으로(RTL) 지원을 추가합니다",
    "AndroidConnectDebuggerAction" to "Android 프로세스에 디버거 연결",
    "AndroidExtractAsIncludeAction" to "하나 이상의 뷰를 별도의 레이아웃으로 추출합니다",
    "AndroidExtractStyleAction" to "레이아웃에서 스타일 관련 속성을 추출하여 새 스타일로 만듭니다",
    "AndroidFindStyleApplicationsAction" to "가능한 곳에서 속성을 Android 스타일 참조로 대체합니다",
    "AndroidInlineIncludeAction" to "포함된 Android 레이아웃을 인라인 처리합니다",
    "AndroidInlineStyleReferenceAction" to "Android 스타일을 인라인 처리합니다",
    "AndroidMigrateBuildConfigFromGradlePropertiesToDsl" to "필요한 모듈에서만 buildConfig를 활성화합니다",
    "AndroidMigrateResValuesFromGradlePropertiesToDsl" to "필요한 모듈에서만 resValues를 활성화합니다",
    "AndroidMigrateToDefaultTargetSdkToCompileSdkValueIfUnset" to "현재 동작을 유지하면서 프로젝트의 targetSdk를 compileSdk로 기본 설정하도록 마이그레이션합니다",
    "AndroidMigrateToNonTransitiveRClassesAction" to "프로젝트가 비전이적(Non-Transitive) R 클래스를 사용하도록 마이그레이션합니다",
    "AndroidMigrateToResourceNamespacesAction" to "리소스 네임스페이스로 마이그레이션합니다",
    "AndroidModularizeAction" to "클래스와 관련 리소스를 다른 모듈로 이동합니다",
    "AndroidUnusedDependenciesAction" to "프로젝트 종속성을 업데이트합니다",
    "AndroidUnusedResourceAction" to "사용하지 않는 리소스를 제거합니다",
    "AndroidX.BaselineProfile.RunGenerate" to "선택한 앱의 베이스라인 프로필을 생성합니다. 생성은 항상 앱 단위로 수행되며 단일 메서드나 클래스에 대해서는 수행할 수 없습니다.",
    "AssembleGradleModule" to "선택한 모듈을 빌드합니다",
    "AssembleGradleProjectWithTests" to "테스트 구성 요소를 포함해 전체 프로젝트를 빌드합니다",
    "AssembleRunConfiguration" to "선택한 실행 구성을 빌드합니다",
    "CPP.ProjectView.ShowFilesUnknownToCMake" to "이 프로젝트의 CMakeLists.txt 파일에 명시되지 않은 파일을 표시합니다",
    "ChangeGradleJdkLocation" to "현재 프로젝트와 선택한 Gradle 루트에 대한 Gradle JDK 위치를 수정합니다. 이 JDK는 Gradle 동기화를 실행하는 데 사용됩니다",
    "ChangeReview.RunChangeReviewForCommitAction" to "AI 에이전트를 사용해 선택한 커밋을 코드 리뷰합니다",
    "ChangeReview.RunChangeReviewForPendingChangesAction" to "AI 에이전트를 사용해 대기 중인 변경사항을 코드 리뷰합니다",
    "CodeReview.NextComment" to "다음으로 보이는 댓글로 이동합니다",
    "CodeReview.PreviousComment" to "이전으로 보이는 댓글로 이동합니다",
    "CollectZippedLogs" to "로그 및 진단 데이터를 수집합니다",
    "Debugger.FocusOnBreakpoint" to "중단점에 도달하면 기본적으로 이 뷰에 포커스를 맞춥니다",
    "Debugger.FocusOnFinish" to "디버그 세션이 끝나면 기본적으로 이 뷰에 포커스를 맞춥니다",
    "Debugger.FreezeActiveThreadAction" to "스레드 실행이 서스펜드됩니다",
    "Debugger.FreezeInactiveThreadsAction" to "다른 스레드의 실행이 서스펜드됩니다",
    "Debugger.FreezeInactiveThreadsAmongSelected" to "그룹 내 비활성 스레드를 서스펜드합니다",
    "Debugger.FreezeSelectedThreads" to "스레드를 서스펜드합니다",
    "Debugger.MarkObject" to "디버거 뷰에서 시각적으로 구분할 수 있도록 객체를 표시/해제합니다",
    "Debugger.ThawActiveThreadAction" to "스레드 실행이 재개됩니다",
    "Debugger.ThawAllThreadsAction" to "다른 스레드의 실행이 재개됩니다",
    "Debugger.ThawSelectedThreads" to "스레드를 재개합니다",
    "DeveloperServices.ConnectionAssistant" to "기기 연결 디버그를 도와줍니다",
    "DeveloperServices.Firebase" to "앱에 Firebase 추가",
    "DeveloperServices.TargetSDKVersionUpgradeAssistant" to "최신 Android SDK로 업그레이드하도록 도와줍니다!",
    "DeveloperServices.UrlAssistant" to "App Links 어시스턴트를 엽니다",
    "DropAnError" to "SHIFT를 누르고 있으면 예외가 연속으로 발생합니다",
    "DropAnErrorWithAttachments" to "SHIFT를 누르고 있으면 여러 첨부 파일이 생성됩니다",
    "DropAnOutOfMemoryError" to "SHIFT를 누르고 있으면 Metaspace에서 OOME가 발생합니다",
    "DropPluginError" to "SHIFT를 누르고 있으면 서드파티 플러그인에서만 발생합니다",
    "Git.CreateNewWorkingTree" to "현재 저장소로부터 새 Git Worktree를 생성합니다",
    "Git.Log.HighlightCherryPickedCommits" to "현재 브랜치로 체리픽되지 않은 커밋을 강조 표시합니다",
    "Git.Show.WorkingTrees" to "도구창에 Worktree를 표시합니다",
    "Git.WorkingTrees.Open" to "Worktree를 프로젝트로 엽니다",
    "Git.WorkingTrees.Refresh" to "Worktree 목록을 새로고침합니다",
    "Git.WorkingTrees.Remove" to "Worktree 삭제…",
    "GitHub.Timeline.DeleteMergedBranch" to "GitHub에서 병합된 브랜치를 삭제합니다",
    "GoogleCloudTesting.RoboScriptRecorder" to "선택한 구성에 대한 Robo 스크립트를 녹화합니다",
    "GoogleCloudTesting.TestRecorder" to "선택한 구성에 대한 Espresso 테스트를 녹화합니다",
    "HelpTopics" to "도움말",
    "IgnoreGradleChanges" to "Gradle 변경사항을 무시하고 동기화 알림을 숨깁니다",
    "LayoutEditor.HelpAssistant" to "레이아웃 편집기의 도움말 패널을 표시/숨김",
    "LayoutEditor.HelpAssistant.ConstraintLayout" to "Constraint Layout 편집기의 도움말 패널을 만듭니다",
    "LayoutEditor.HelpAssistant.Full" to "레이아웃 편집기의 도움말 패널을 표시/숨김",
    "LayoutEditor.HelpAssistant.MotionLayout" to "Motion Layout 편집기의 도움말 패널을 만듭니다",
    "LegacyNewAndroidComponent" to "기타 카테고리에서 새 Android 객체를 생성합니다",
    "Logcat.ClearLogcat" to "Logcat 패널과 기기의 logcat 버퍼를 지웁니다",
    "Logcat.PauseResumeLogcat" to "Logcat 패널을 일시정지하거나 재개합니다",
    "Logcat.RestartLogcat" to "Logcat 모니터링을 재시작합니다",
    "Logcat.ToggleSoftWrap" to "Logcat 메시지의 자동 줄바꿈을 전환합니다",
    "Logcat.ToggleViewFormat" to "표준 보기와 축소 보기를 전환합니다",
    "MakeGradleProject" to "전체 프로젝트를 빌드합니다",
    "MemoryView.SwitchUpdateMode" to "디버거 일시 정지 시 클래스를 로드합니다(디버거 스테핑 오버헤드가 늘어날 수 있음)",
    "NavEditor.HelpAssistant" to "탐색 편집기의 도움말 패널을 표시합니다",
    "NewAndroidImageAsset" to "이미지 애셋을 만들기 위해 Asset Studio를 엽니다",
    "NewAndroidVectorAsset" to "이미지 애셋을 만들기 위해 Vector Asset Studio를 엽니다",
    "NewModule" to "프로젝트에 새 모듈을 추가합니다",
    "NewModuleInGroup" to "프로젝트에 새 모듈을 추가합니다",
    "NewVersionCatalogFile" to "새 버전 카탈로그 파일을 생성합니다",
    "ResetUserIdAction" to "데이터 공유 사용자 식별자 재설정",
    "ResetWindowsDefenderNotification" to "현재 프로젝트에 대해 Microsoft Defender 상태 검사를 다시 실행하고 알림을 다시 표시합니다",
    "ResourceExplorer.CopyValue" to "리소스 값을 클립보드에 복사합니다",
    "ResourceExplorer.open" to "리소스 관리자를 엽니다",
    "ResourceExplorer.show" to "선택한 파일을 리소스 관리자에 표시합니다",
    "SeNewSearchToggleAction" to "새로운 원격 친화적 Search Everywhere 구현을 사용합니다",
    "SelectProjectAction" to "Firebase 프로젝트와 기기를 선택할 수 있는 기기 스트리밍 대화상자를 엽니다",
    "ShowNextEditPredictionMenuAction" to "다음 편집 예측 상태 표시줄 메뉴를 표시합니다",
    "Table-selectFirstColumn" to "첫 번째 열을 선택합니다",
    "Table-selectFirstColumnExtendSelection" to "첫 번째 열로 스크롤하고 해당 열들을 선택 영역에 추가합니다",
    "Table-selectLastColumn" to "마지막 열을 선택합니다",
    "Table-selectLastColumnExtendSelection" to "마지막 열로 스크롤하고 해당 열들을 선택 영역에 추가합니다",
    "Terminal.AiAgents.AgentSelector" to "새 세션을 시작할 AI 에이전트를 선택합니다",
    "Terminal.AiAgents.ChevronSelector" to "새 세션을 시작할 AI 에이전트를 선택합니다",
    "XDebugger.CompareValueWithClipboard" to "선택한 노드의 값을 클립보드와 비교합니다",
    "XDebugger.CopyName" to "선택한 노드의 이름을 클립보드에 복사합니다",
    "XDebugger.CopyValue" to "선택한 노드의 값을 클립보드에 복사합니다",
    "XDebugger.DisableAllButThisBreakpoint" to "커서가 있는 줄을 제외한 모든 중단점을 비활성화합니다",
    "XDebugger.Inline" to "사용 가능한 디버거 세션 값을 에디터 안에 표시합니다",
    "XDebugger.JumpToSource" to "선택한 항목의 소스를 엽니다",
    "XDebugger.JumpToTypeSource" to "선택한 값의 타입 소스를 엽니다",
    "XDebugger.RemoveAllButThisBreakpoint" to "커서가 있는 줄을 제외한 모든 중단점을 제거합니다",
    "XDebugger.SetValue" to "선택한 노드의 값을 수정합니다",
    "XDebugger.ToggleSortValues" to "디버거 뷰에서 값을 알파벳순으로 정렬합니다",
    "action.android.backup" to "앱 데이터를 파일로 백업합니다",
    "action.android.backup.foreground.app" to "앱 데이터를 파일로 백업합니다",
    "action.android.restore" to "파일에서 앱 데이터를 복원합니다",
    "action.android.restore.file" to "파일에서 앱 데이터를 복원합니다",
    "action.android.restore.group" to "파일에서 앱 데이터를 복원합니다",
    "aiplugin.mcp.client.listTools" to "MCP 도구 목록",
    "android.deploy.ApplyChanges" to "리소스 및 코드 변경사항을 적용하고 액티비티를 재시작합니다",
    "android.deploy.CodeSwap" to "재시작 없이 코드 변경사항만 적용합니다",
    "android.deploy.DebugWithoutBuild" to "빌드 없이 애플리케이션을 배포하고 디버그합니다",
    "android.deploy.RunWithoutBuild" to "빌드 없이 애플리케이션을 배포하고 실행합니다",
    "android.device.back.button" to "기기의 뒤로 버튼을 누릅니다",
    "android.device.home.button" to "기기의 홈 버튼을 누릅니다",
    "android.device.overview.button" to "기기의 개요 버튼을 누릅니다",
    "android.device.postures" to "기기가 정의한 상태 중 하나를 선택하여 앱의 반응을 테스트합니다",
    "android.device.power.and.volume.up.button" to "기기의 전원 버튼과 볼륨 올리기 버튼을 동시에 누릅니다",
    "android.device.power.button" to "기기의 전원 버튼을 누릅니다",
    "android.device.reservation.end" to "예약을 종료하고 기기를 반환합니다",
    "android.device.reservation.extend" to "기기 예약을 연장합니다",
    "android.device.rotate.left" to "기기를 반시계 방향으로 90도 회전합니다",
    "android.device.rotate.right" to "기기를 시계 방향으로 90도 회전합니다",
    "android.device.screen.record" to "기기 화면의 동영상을 녹화합니다",
    "android.device.screenshot" to "기기에서 스크린샷을 가져옵니다",
    "android.device.sleep" to "기기의 손바닥(Palm) 제스처를 시뮬레이션합니다",
    "android.device.volume.down.button" to "기기의 볼륨 내리기 버튼을 누릅니다",
    "android.device.volume.up.button" to "기기의 볼륨 올리기 버튼을 누릅니다",
    "android.device.wear.whs" to "Wear Health Services 패널을 엽니다",
    "android.device.wear1.button" to "기기의 첫 번째 버튼을 누릅니다",
    "android.device.wear2.button" to "기기의 두 번째 버튼을 누릅니다",
    "android.emulator.display.mode" to "디스플레이 모드를 선택합니다",
    "android.emulator.display.mode.foldable" to "일반적인 폴더블 기기 크기에 맞게 디스플레이 크기를 변경합니다",
    "android.emulator.display.mode.phone" to "일반적인 휴대폰 크기에 맞게 디스플레이 크기를 변경합니다",
    "android.emulator.display.mode.tablet" to "일반적인 태블릿 크기에 맞게 디스플레이 크기를 변경합니다",
    "android.emulator.environment.custom" to "사용자 지정 환경을 선택합니다",
    "android.emulator.environment.darkness" to "완전히 어두운 환경을 선택합니다",
    "android.emulator.environments" to "Intelligent Eyewear 기기의 환경을 선택합니다",
    "android.emulator.extended.controls" to "에뮬레이터 확장 컨트롤을 표시합니다",
    "android.emulator.glasses.camera.button" to "기기의 카메라 버튼을 누릅니다",
    "android.emulator.glasses.display.button" to "기기의 디스플레이 버튼을 누릅니다",
    "android.emulator.glasses1.button" to "기기의 카메라 버튼을 누릅니다",
    "android.emulator.glasses2.button" to "기기의 디스플레이 버튼을 누릅니다",
    "android.emulator.snapshots" to "에뮬레이터 스냅샷을 생성, 로드, 이름 변경 또는 삭제합니다",
    "android.emulator.tilt" to "기기의 기울이기(Tilt) 제스처를 시뮬레이션합니다",
    "android.emulator.virtual.sensors" to "기기의 가상 센서 컨트롤을 표시합니다",
    "android.streaming.benchmark" to "내장 에뮬레이터 또는 실제 기기 미러링의 성능을 측정합니다",
    "android.streaming.hardware.input" to "키보드와 마우스 이벤트를 기기로 투명하게 전달하도록 설정합니다",
    "android.streaming.microphone.input" to "에뮬레이터를 시스템 마이크에 연결하거나 연결을 해제합니다",
    "android.streaming.ui.settings" to "자주 쓰는 Android 설정으로 가는 바로가기입니다",
    "android.streaming.xr.eye.tracking" to "마우스로 시선 추적을 시뮬레이션합니다. 방향키로 시야 방향을 제어합니다.",
    "android.streaming.xr.hand.tracking" to "마우스로 손 추적을 시뮬레이션합니다. 방향키로 시야 방향을 제어합니다.",
    "android.streaming.xr.input.mode.dropdown" to "실행 중인 앱과 상호작용할 모드를 선택합니다",
    "android.streaming.xr.interaction" to "마우스와 키보드로 실행 중인 앱과 상호작용합니다",
    "android.streaming.xr.interaction.eye" to "마우스로 시선 추적을 시뮬레이션합니다. 방향키로 시야 방향을 제어합니다.",
    "android.streaming.xr.interaction.hand" to "마우스로 손 추적을 시뮬레이션합니다. 방향키로 시야 방향을 제어합니다.",
    "android.streaming.xr.interaction.mouse" to "마우스와 키보드 이벤트를 기기로 전달합니다",
    "android.streaming.xr.location.in.space.xy" to "마우스를 드래그하면 가상 공간에서 좌우/상하로 이동합니다. 방향키로 시야 방향을, WASDQE 키로 가상 공간에서의 위치를 제어합니다.",
    "android.streaming.xr.location.in.space.z" to "마우스를 세로로 드래그하면 가상 공간에서 앞뒤로 이동합니다.",
    "android.streaming.xr.passthrough" to "패스스루를 켜거나 끕니다",
    "android.streaming.xr.passthrough.toggle" to "패스스루를 켜거나 끕니다",
    "android.streaming.xr.recenter" to "시야를 기본값으로 재설정합니다",
    "android.streaming.xr.view.direction" to "마우스 드래그와 방향키로 시야 방향을 제어합니다. WASDQE 키로 가상 공간에서의 위치를 제어합니다.",
    "android.streaming.zoom.actual" to "실제 크기로 확대/축소합니다",
    "android.streaming.zoom.fit" to "창에 맞도록 뷰를 확대/축소합니다",
    "android.streaming.zoom.fit.inner" to "사용 가능한 공간에 디스플레이 이미지가 맞도록 뷰를 확대/축소합니다",
    "android.streaming.zoom.in" to "확대합니다",
    "android.streaming.zoom.out" to "축소합니다",
    "com.android.build.attribution.ui.OpenBuildAnalyzerAction" to "빌드 분석기 열기(보고서를 표시하려면 빌드가 성공해야 함)",
    "com.android.build.attribution.ui.OpenBuildAnalyzerResultsAction" to "이전 빌드 결과로 빌드 분석기 열기",
    "com.android.screenshottest.action.UpdateReferenceImagesAction" to "거터 아이콘에서 참조 이미지를 추가/업데이트합니다",
    "com.android.screenshottest.action.UpdateReferenceImagesFromTestPanelAction" to "스크린샷 테스트의 참조 이미지를 업데이트합니다",
    "com.android.screenshottest.action.UpdateReferenceImagesInClassAction" to "클래스 내 모든 스크린샷 테스트의 참조 이미지를 추가/업데이트합니다",
    "com.android.screenshottest.action.UpdateReferenceImagesInDirectoryAction" to "디렉터리 내 모든 스크린샷 테스트의 참조 이미지를 추가/업데이트합니다",
    "com.android.tools.idea.actions.HideAndroidBannerAction" to "Gradle 프로젝트 알림 배너를 닫습니다",
    "com.android.tools.idea.layoutinspector.toggle.layout.inspector.action" to "이 기기에 대한 레이아웃 검사를 켜거나 끕니다",
    "com.google.studiobot.container.trajectory.ActivateChatAction" to "에이전트 채팅 창을 열거나, 열려 있는 에이전트 탭들을 순환합니다",
    "com.google.tools.intellij.aiplugin.action.SelectGcpProjectAction" to "Gemini Code Assist 클라우드 프로젝트를 선택합니다",
    "sml.AnalyzeThreadSafety" to "선택한 파일의 스레드 안전성 상태를 분석합니다",
    "sml.GenerateReadmeAction" to "선택한 파일에 대한 README를 마크다운으로 생성합니다",
    "sml.KeepChange" to "이 변경사항을 유지합니다",
    "sml.MergeConflictsWithAgentAction" to "현재 저장소의 충돌 병합을 에이전트에게 요청합니다",
    "sml.ResumeMigrationAction" to "디스크에 저장된 재개용 아티팩트로 구성된 마이그레이션 에이전트를 즉시 불러옵니다",
    "sml.RevertChange" to "이 변경사항을 되돌립니다",
    "sml.SuggestCommitMessageAction" to "변경사항을 요약하여 커밋 메시지를 제안합니다",
    "sml.studiobot.quick.edit" to "인라인 AI 편집기를 엽니다",
)
